root@capytol:~# ls -la /home/mayor
total 20
drwxr-xr-x 1 root root 4096 Apr  8 17:06 .
drwxr-xr-x 1 root root 4096 Apr  7 17:50 ..
-rw-r--r-- 1 root root   31 Apr  7 17:50 .inputrc
drwxrwxr-x 3 1001 1001 4096 Apr  7 17:51 Documents
root@capytol:~# find / -name ".*" 2>/dev/null
/etc/.pwd.lock
/etc/skel/.bashrc
/etc/skel/.profile
/etc/skel/.bash_logout
/home/ubuntu/.bashrc
/home/ubuntu/.profile
/home/ubuntu/.bash_logout
/home/mayor/.inputrc
/root/.bashrc
/root/.profile
/usr/lib/modules/6.8.0-53-generic/vdso/.build-id
/usr/share/vim/vim91/pack/dist/opt/editorconfig/.editorconfig
/sys/module/efi_pstore/notes/.note.Linux
/sys/module/efi_pstore/notes/.note.gnu.build-id
/sys/module/efi_pstore/sections/.note.Linux
/sys/module/efi_pstore/sections/.strtab
/sys/module/efi_pstore/sections/.exit.text
/sys/module/efi_pstore/sections/.exit.data
/sys/module/efi_pstore/sections/.bss
/sys/module/efi_pstore/sections/.return_sites
/sys/module/efi_pstore/sections/.gnu.linkonce.this_module
/sys/module/efi_pstore/sections/.symtab
/sys/module/efi_pstore/sections/.rodata
/sys/module/efi_pstore/sections/.init.text
/sys/module/efi_pstore/sections/.note.gnu.build-id
/sys/module/efi_pstore/sections/.text
/sys/module/efi_pstore/sections/.init.data
/sys/module/efi_pstore/sections/.call_sites
/sys/module/efi_pstore/sections/.data
/sys/module/efi_pstore/sections/.rodata.str1.1
/sys/module/efi_pstore/sections/.text.unlikely
/sys/module/efi_pstore/sections/.rodata.str1.8
/sys/module/xor/notes/.note.Linux
/sys/module/xor/notes/.note.gnu.build-id
/sys/module/xor/sections/.note.Linux
/sys/module/xor/sections/.static_call_sites
/sys/module/xor/sections/.strtab
/sys/module/xor/sections/.exit.text
/sys/module/xor/sections/.exit.data
/sys/module/xor/sections/.bss
/sys/module/xor/sections/.return_sites
/sys/module/xor/sections/.gnu.linkonce.this_module
/sys/module/xor/sections/.symtab
/sys/module/xor/sections/.init.text
/sys/module/xor/sections/.note.gnu.build-id
/sys/module/xor/sections/.text
/sys/module/xor/sections/.init.data
/sys/module/xor/sections/.call_sites
/sys/module/xor/sections/.data
/sys/module/xor/sections/.rodata.str1.1
/sys/module/xor/sections/.retpoline_sites
/sys/module/xor/sections/.rodata.str1.8
/sys/module/virtio_rng/notes/.note.Linux
/sys/module/virtio_rng/notes/.note.gnu.build-id
/sys/module/virtio_rng/sections/.note.Linux
/sys/module/virtio_rng/sections/.strtab
/sys/module/virtio_rng/sections/.exit.text
/sys/module/virtio_rng/sections/.exit.data
/sys/module/virtio_rng/sections/.return_sites
/sys/module/virtio_rng/sections/.gnu.linkonce.this_module
/sys/module/virtio_rng/sections/.symtab
/sys/module/virtio_rng/sections/.rodata
/sys/module/virtio_rng/sections/.init.text
/sys/module/virtio_rng/sections/.note.gnu.build-id
/sys/module/virtio_rng/sections/.text
/sys/module/virtio_rng/sections/.init.data
/sys/module/virtio_rng/sections/.call_sites
/sys/module/virtio_rng/sections/.data
/sys/module/virtio_rng/sections/.rodata.str1.1
/sys/module/virtio_rng/sections/.text.unlikely
/sys/module/virtio_rng/sections/.retpoline_sites
/sys/module/virtio_rng/sections/.rodata.str1.8
/sys/module/xt_conntrack/notes/.note.Linux
/sys/module/xt_conntrack/notes/.note.gnu.build-id
/sys/module/xt_conntrack/sections/.data..read_mostly
/sys/module/xt_conntrack/sections/.note.Linux
/sys/module/xt_conntrack/sections/.strtab
/sys/module/xt_conntrack/sections/.exit.text
/sys/module/xt_conntrack/sections/.exit.data
/sys/module/xt_conntrack/sections/.return_sites
/sys/module/xt_conntrack/sections/.gnu.linkonce.this_module
/sys/module/xt_conntrack/sections/.symtab
/sys/module/xt_conntrack/sections/.rodata
/sys/module/xt_conntrack/sections/.init.text
/sys/module/xt_conntrack/sections/.note.gnu.build-id
/sys/module/xt_conntrack/sections/.text
/sys/module/xt_conntrack/sections/.init.data
/sys/module/xt_conntrack/sections/.call_sites
/sys/module/xt_conntrack/sections/.data
/sys/module/xt_conntrack/sections/.rodata.str1.8
/sys/module/raid1/notes/.note.Linux
/sys/module/raid1/notes/.note.gnu.build-id
/sys/module/raid1/sections/.note.Linux
/sys/module/raid1/sections/.static_call_sites
/sys/module/raid1/sections/.strtab
/sys/module/raid1/sections/.exit.data
/sys/module/raid1/sections/.return_sites
/sys/module/raid1/sections/.gnu.linkonce.this_module
/sys/module/raid1/sections/.symtab
/sys/module/raid1/sections/.rodata
/sys/module/raid1/sections/.init.text
/sys/module/raid1/sections/.note.gnu.build-id
/sys/module/raid1/sections/.text
/sys/module/raid1/sections/.init.data
/sys/module/raid1/sections/.call_sites
/sys/module/raid1/sections/.data
/sys/module/raid1/sections/.smp_locks
/sys/module/raid1/sections/.rodata.str1.1
/sys/module/raid1/sections/.text.unlikely
/sys/module/raid1/sections/.retpoline_sites
/sys/module/raid1/sections/.rodata.str1.8
/sys/module/cpuid/notes/.note.Linux
/sys/module/cpuid/notes/.note.gnu.build-id
/sys/module/cpuid/sections/.altinstructions
/sys/module/cpuid/sections/.note.Linux
/sys/module/cpuid/sections/.strtab
/sys/module/cpuid/sections/.exit.text
/sys/module/cpuid/sections/.exit.data
/sys/module/cpuid/sections/.bss
/sys/module/cpuid/sections/.return_sites
/sys/module/cpuid/sections/.gnu.linkonce.this_module
/sys/module/cpuid/sections/.symtab
/sys/module/cpuid/sections/.rodata
/sys/module/cpuid/sections/.init.text
/sys/module/cpuid/sections/.note.gnu.build-id
/sys/module/cpuid/sections/.text
/sys/module/cpuid/sections/.init.data
/sys/module/cpuid/sections/.call_sites
/sys/module/cpuid/sections/.data
/sys/module/cpuid/sections/.altinstr_replacement
/sys/module/cpuid/sections/.rodata.str1.1
/sys/module/cpuid/sections/.rodata.str1.8
/sys/module/nf_conntrack/notes/.note.Linux
/sys/module/nf_conntrack/notes/.note.gnu.build-id
/sys/module/nf_conntrack/sections/.data.once
/sys/module/nf_conntrack/sections/.data..read_mostly
/sys/module/nf_conntrack/sections/.BTF_ids
/sys/module/nf_conntrack/sections/.note.Linux
/sys/module/nf_conntrack/sections/.static_call_sites
/sys/module/nf_conntrack/sections/.strtab
/sys/module/nf_conntrack/sections/.exit.text
/sys/module/nf_conntrack/sections/.exit.data
/sys/module/nf_conntrack/sections/.bss
/sys/module/nf_conntrack/sections/.return_sites
/sys/module/nf_conntrack/sections/.gnu.linkonce.this_module
/sys/module/nf_conntrack/sections/.symtab
/sys/module/nf_conntrack/sections/.rodata
/sys/module/nf_conntrack/sections/.init.text
/sys/module/nf_conntrack/sections/.note.gnu.build-id
/sys/module/nf_conntrack/sections/.text
/sys/module/nf_conntrack/sections/.init.data
/sys/module/nf_conntrack/sections/.call_sites
/sys/module/nf_conntrack/sections/.data
/sys/module/nf_conntrack/sections/.data..cacheline_aligned
/sys/module/nf_conntrack/sections/.smp_locks
/sys/module/nf_conntrack/sections/.rodata.str1.1
/sys/module/nf_conntrack/sections/.text.unlikely
/sys/module/nf_conntrack/sections/.rodata.cst2
/sys/module/nf_conntrack/sections/.retpoline_sites
/sys/module/nf_conntrack/sections/.rodata.str1.8
/sys/module/libahci/notes/.note.Linux
/sys/module/libahci/notes/.note.gnu.build-id
/sys/module/libahci/sections/.data..read_mostly
/sys/module/libahci/sections/.note.Linux
/sys/module/libahci/sections/.strtab
/sys/module/libahci/sections/.bss
/sys/module/libahci/sections/.return_sites
/sys/module/libahci/sections/.gnu.linkonce.this_module
/sys/module/libahci/sections/.symtab
/sys/module/libahci/sections/.rodata
/sys/module/libahci/sections/.note.gnu.build-id
/sys/module/libahci/sections/.text
/sys/module/libahci/sections/.call_sites
/sys/module/libahci/sections/.data
/sys/module/libahci/sections/.rodata.str1.1
/sys/module/libahci/sections/.text.unlikely
/sys/module/libahci/sections/.retpoline_sites
/sys/module/libahci/sections/.rodata.str1.8
/sys/module/irqbypass/notes/.note.Linux
/sys/module/irqbypass/notes/.note.gnu.build-id
/sys/module/irqbypass/sections/.note.Linux
/sys/module/irqbypass/sections/.static_call_sites
/sys/module/irqbypass/sections/.strtab
/sys/module/irqbypass/sections/.return_sites
/sys/module/irqbypass/sections/.gnu.linkonce.this_module
/sys/module/irqbypass/sections/.symtab
/sys/module/irqbypass/sections/.note.gnu.build-id
/sys/module/irqbypass/sections/.text
/sys/module/irqbypass/sections/.call_sites
/sys/module/irqbypass/sections/.data
/sys/module/irqbypass/sections/.retpoline_sites
/sys/module/async_pq/notes/.note.Linux
/sys/module/async_pq/notes/.note.gnu.build-id
/sys/module/async_pq/sections/.note.Linux
/sys/module/async_pq/sections/.strtab
/sys/module/async_pq/sections/.exit.text
/sys/module/async_pq/sections/.exit.data
/sys/module/async_pq/sections/.bss
/sys/module/async_pq/sections/.return_sites
/sys/module/async_pq/sections/.gnu.linkonce.this_module
/sys/module/async_pq/sections/.symtab
/sys/module/async_pq/sections/.rodata
/sys/module/async_pq/sections/.init.text
/sys/module/async_pq/sections/.note.gnu.build-id
/sys/module/async_pq/sections/.text
/sys/module/async_pq/sections/.init.data
/sys/module/async_pq/sections/.call_sites
/sys/module/async_pq/sections/.data
/sys/module/async_pq/sections/.smp_locks
/sys/module/async_pq/sections/.rodata.str1.1
/sys/module/async_pq/sections/.text.unlikely
/sys/module/async_pq/sections/.retpoline_sites
/sys/module/async_pq/sections/.rodata.str1.8
/sys/module/cryptd/notes/.note.Linux
/sys/module/cryptd/notes/.note.gnu.build-id
/sys/module/cryptd/sections/.note.Linux
/sys/module/cryptd/sections/.strtab
/sys/module/cryptd/sections/.exit.text
/sys/module/cryptd/sections/.exit.data
/sys/module/cryptd/sections/.bss
/sys/module/cryptd/sections/.return_sites
/sys/module/cryptd/sections/.gnu.linkonce.this_module
/sys/module/cryptd/sections/.symtab
/sys/module/cryptd/sections/.rodata
/sys/module/cryptd/sections/.init.text
/sys/module/cryptd/sections/.note.gnu.build-id
/sys/module/cryptd/sections/.text
/sys/module/cryptd/sections/.init.data
/sys/module/cryptd/sections/.call_sites
/sys/module/cryptd/sections/.data
/sys/module/cryptd/sections/.smp_locks
/sys/module/cryptd/sections/.rodata.str1.1
/sys/module/cryptd/sections/.retpoline_sites
/sys/module/cryptd/sections/.rodata.str1.8
/sys/module/ecdh_generic/notes/.note.Linux
/sys/module/ecdh_generic/notes/.note.gnu.build-id
/sys/module/ecdh_generic/sections/.data.once
/sys/module/ecdh_generic/sections/.note.Linux
/sys/module/ecdh_generic/sections/.strtab
/sys/module/ecdh_generic/sections/.exit.text
/sys/module/ecdh_generic/sections/.exit.data
/sys/module/ecdh_generic/sections/.bss
/sys/module/ecdh_generic/sections/.return_sites
/sys/module/ecdh_generic/sections/.gnu.linkonce.this_module
/sys/module/ecdh_generic/sections/.symtab
/sys/module/ecdh_generic/sections/.init.text
/sys/module/ecdh_generic/sections/.note.gnu.build-id
/sys/module/ecdh_generic/sections/.text
/sys/module/ecdh_generic/sections/.init.data
/sys/module/ecdh_generic/sections/.call_sites
/sys/module/ecdh_generic/sections/.data
/sys/module/ecdh_generic/sections/.rodata.str1.1
/sys/module/ecdh_generic/sections/.text.unlikely
/sys/module/ecdh_generic/sections/.rodata.str1.8
/sys/module/crypto_simd/notes/.note.Linux
/sys/module/crypto_simd/notes/.note.gnu.build-id
/sys/module/crypto_simd/sections/.note.Linux
/sys/module/crypto_simd/sections/.strtab
/sys/module/crypto_simd/sections/.return_sites
/sys/module/crypto_simd/sections/.gnu.linkonce.this_module
/sys/module/crypto_simd/sections/.symtab
/sys/module/crypto_simd/sections/.note.gnu.build-id
/sys/module/crypto_simd/sections/.text
/sys/module/crypto_simd/sections/.call_sites
/sys/module/crypto_simd/sections/.data
/sys/module/crypto_simd/sections/.rodata.str1.1
/sys/module/crypto_simd/sections/.rodata.str1.8
/sys/module/async_memcpy/notes/.note.Linux
/sys/module/async_memcpy/notes/.note.gnu.build-id
/sys/module/async_memcpy/sections/.note.Linux
/sys/module/async_memcpy/sections/.static_call_sites
/sys/module/async_memcpy/sections/.strtab
/sys/module/async_memcpy/sections/.return_sites
/sys/module/async_memcpy/sections/.gnu.linkonce.this_module
/sys/module/async_memcpy/sections/.symtab
/sys/module/async_memcpy/sections/.rodata
/sys/module/async_memcpy/sections/.note.gnu.build-id
/sys/module/async_memcpy/sections/.text
/sys/module/async_memcpy/sections/.call_sites
/sys/module/async_memcpy/sections/.data
/sys/module/async_memcpy/sections/.smp_locks
/sys/module/async_memcpy/sections/.rodata.str1.1
/sys/module/async_memcpy/sections/.text.unlikely
/sys/module/async_memcpy/sections/.retpoline_sites
/sys/module/async_memcpy/sections/.rodata.str1.8
/sys/module/nfnetlink/notes/.note.Linux
/sys/module/nfnetlink/notes/.note.gnu.build-id
/sys/module/nfnetlink/sections/.data..read_mostly
/sys/module/nfnetlink/sections/.note.Linux
/sys/module/nfnetlink/sections/.strtab
/sys/module/nfnetlink/sections/.exit.text
/sys/module/nfnetlink/sections/.exit.data
/sys/module/nfnetlink/sections/.bss
/sys/module/nfnetlink/sections/.return_sites
/sys/module/nfnetlink/sections/.gnu.linkonce.this_module
/sys/module/nfnetlink/sections/.symtab
/sys/module/nfnetlink/sections/.rodata
/sys/module/nfnetlink/sections/.init.text
/sys/module/nfnetlink/sections/.note.gnu.build-id
/sys/module/nfnetlink/sections/.text
/sys/module/nfnetlink/sections/.init.data
/sys/module/nfnetlink/sections/.call_sites
/sys/module/nfnetlink/sections/.data
/sys/module/nfnetlink/sections/.rodata.str1.1
/sys/module/nfnetlink/sections/.retpoline_sites
/sys/module/nfnetlink/sections/.rodata.str1.8
/sys/module/ecc/notes/.note.Linux
/sys/module/ecc/notes/.note.gnu.build-id
/sys/module/ecc/sections/.note.Linux
/sys/module/ecc/sections/.strtab
/sys/module/ecc/sections/.return_sites
/sys/module/ecc/sections/.gnu.linkonce.this_module
/sys/module/ecc/sections/.symtab
/sys/module/ecc/sections/.rodata
/sys/module/ecc/sections/.note.gnu.build-id
/sys/module/ecc/sections/.text
/sys/module/ecc/sections/.call_sites
/sys/module/ecc/sections/.data
/sys/module/ecc/sections/.smp_locks
/sys/module/ecc/sections/.rodata.str1.1
/sys/module/ecc/sections/.retpoline_sites
/sys/module/ecc/sections/.rodata.str1.8
/sys/module/async_tx/notes/.note.Linux
/sys/module/async_tx/notes/.note.gnu.build-id
/sys/module/async_tx/sections/.note.Linux
/sys/module/async_tx/sections/.strtab
/sys/module/async_tx/sections/.exit.text
/sys/module/async_tx/sections/.exit.data
/sys/module/async_tx/sections/.return_sites
/sys/module/async_tx/sections/.gnu.linkonce.this_module
/sys/module/async_tx/sections/.symtab
/sys/module/async_tx/sections/.rodata
/sys/module/async_tx/sections/.init.text
/sys/module/async_tx/sections/.note.gnu.build-id
/sys/module/async_tx/sections/.text
/sys/module/async_tx/sections/.init.data
/sys/module/async_tx/sections/.call_sites
/sys/module/async_tx/sections/.rodata.str1.1
/sys/module/async_tx/sections/.retpoline_sites
/sys/module/async_tx/sections/.rodata.str1.8
/sys/module/input_leds/notes/.note.Linux
/sys/module/input_leds/notes/.note.gnu.build-id
/sys/module/input_leds/sections/.note.Linux
/sys/module/input_leds/sections/.strtab
/sys/module/input_leds/sections/.exit.text
/sys/module/input_leds/sections/.exit.data
/sys/module/input_leds/sections/.return_sites
/sys/module/input_leds/sections/.gnu.linkonce.this_module
/sys/module/input_leds/sections/.symtab
/sys/module/input_leds/sections/.rodata
/sys/module/input_leds/sections/.init.text
/sys/module/input_leds/sections/.note.gnu.build-id
/sys/module/input_leds/sections/.text
/sys/module/input_leds/sections/.init.data
/sys/module/input_leds/sections/.call_sites
/sys/module/input_leds/sections/.data
/sys/module/input_leds/sections/.rodata.str1.1
/sys/module/input_leds/sections/.rodata.str1.8
/sys/module/tcp_diag/notes/.note.Linux
/sys/module/tcp_diag/notes/.note.gnu.build-id
/sys/module/tcp_diag/sections/.data.once
/sys/module/tcp_diag/sections/.note.Linux
/sys/module/tcp_diag/sections/.strtab
/sys/module/tcp_diag/sections/.exit.text
/sys/module/tcp_diag/sections/.exit.data
/sys/module/tcp_diag/sections/.return_sites
/sys/module/tcp_diag/sections/.gnu.linkonce.this_module
/sys/module/tcp_diag/sections/.symtab
/sys/module/tcp_diag/sections/.rodata
/sys/module/tcp_diag/sections/.init.text
/sys/module/tcp_diag/sections/.note.gnu.build-id
/sys/module/tcp_diag/sections/.text
/sys/module/tcp_diag/sections/.init.data
/sys/module/tcp_diag/sections/.call_sites
/sys/module/tcp_diag/sections/.data
/sys/module/tcp_diag/sections/.rodata.str1.1
/sys/module/tcp_diag/sections/.text.unlikely
/sys/module/tcp_diag/sections/.retpoline_sites
/sys/module/tcp_diag/sections/.rodata.str1.8
/sys/module/nf_nat/notes/.note.Linux
/sys/module/nf_nat/notes/.note.gnu.build-id
/sys/module/nf_nat/sections/.data.once
/sys/module/nf_nat/sections/.data..read_mostly
/sys/module/nf_nat/sections/.BTF_ids
/sys/module/nf_nat/sections/.note.Linux
/sys/module/nf_nat/sections/.strtab
/sys/module/nf_nat/sections/.exit.text
/sys/module/nf_nat/sections/.exit.data
/sys/module/nf_nat/sections/.bss
/sys/module/nf_nat/sections/.return_sites
/sys/module/nf_nat/sections/.gnu.linkonce.this_module
/sys/module/nf_nat/sections/.symtab
/sys/module/nf_nat/sections/.rodata
/sys/module/nf_nat/sections/.init.text
/sys/module/nf_nat/sections/.note.gnu.build-id
/sys/module/nf_nat/sections/.text
/sys/module/nf_nat/sections/.init.data
/sys/module/nf_nat/sections/.call_sites
/sys/module/nf_nat/sections/.data
/sys/module/nf_nat/sections/.smp_locks
/sys/module/nf_nat/sections/.rodata.str1.1
/sys/module/nf_nat/sections/.retpoline_sites
/sys/module/nf_nat/sections/.rodata.str1.8
/sys/module/af_packet_diag/notes/.note.Linux
/sys/module/af_packet_diag/notes/.note.gnu.build-id
/sys/module/af_packet_diag/sections/.note.Linux
/sys/module/af_packet_diag/sections/.strtab
/sys/module/af_packet_diag/sections/.exit.text
/sys/module/af_packet_diag/sections/.exit.data
/sys/module/af_packet_diag/sections/.return_sites
/sys/module/af_packet_diag/sections/.gnu.linkonce.this_module
/sys/module/af_packet_diag/sections/.symtab
/sys/module/af_packet_diag/sections/.rodata
/sys/module/af_packet_diag/sections/.init.text
/sys/module/af_packet_diag/sections/.note.gnu.build-id
/sys/module/af_packet_diag/sections/.text
/sys/module/af_packet_diag/sections/.init.data
/sys/module/af_packet_diag/sections/.call_sites
/sys/module/af_packet_diag/sections/.rodata.str1.1
/sys/module/bridge/notes/.note.Linux
/sys/module/bridge/notes/.note.gnu.build-id
/sys/module/bridge/sections/.altinstructions
/sys/module/bridge/sections/.data.once
/sys/module/bridge/sections/.data..read_mostly
/sys/module/bridge/sections/.note.Linux
/sys/module/bridge/sections/.static_call_sites
/sys/module/bridge/sections/.strtab
/sys/module/bridge/sections/.exit.text
/sys/module/bridge/sections/.exit.data
/sys/module/bridge/sections/.bss
/sys/module/bridge/sections/.return_sites
/sys/module/bridge/sections/.gnu.linkonce.this_module
/sys/module/bridge/sections/.symtab
/sys/module/bridge/sections/.rodata
/sys/module/bridge/sections/.init.text
/sys/module/bridge/sections/.note.gnu.build-id
/sys/module/bridge/sections/.text
/sys/module/bridge/sections/.init.data
/sys/module/bridge/sections/.call_sites
/sys/module/bridge/sections/.data
/sys/module/bridge/sections/.altinstr_replacement
/sys/module/bridge/sections/.smp_locks
/sys/module/bridge/sections/.rodata.str1.1
/sys/module/bridge/sections/.text.unlikely
/sys/module/bridge/sections/.rodata.cst2
/sys/module/bridge/sections/.retpoline_sites
/sys/module/bridge/sections/.rodata.str1.8
/sys/module/nft_compat/notes/.note.Linux
/sys/module/nft_compat/notes/.note.gnu.build-id
/sys/module/nft_compat/sections/.data..read_mostly
/sys/module/nft_compat/sections/.note.Linux
/sys/module/nft_compat/sections/.strtab
/sys/module/nft_compat/sections/.exit.text
/sys/module/nft_compat/sections/.exit.data
/sys/module/nft_compat/sections/.return_sites
/sys/module/nft_compat/sections/.gnu.linkonce.this_module
/sys/module/nft_compat/sections/.symtab
/sys/module/nft_compat/sections/.rodata
/sys/module/nft_compat/sections/.init.text
/sys/module/nft_compat/sections/.note.gnu.build-id
/sys/module/nft_compat/sections/.text
/sys/module/nft_compat/sections/.init.data
/sys/module/nft_compat/sections/.call_sites
/sys/module/nft_compat/sections/.data
/sys/module/nft_compat/sections/.rodata.str1.1
/sys/module/nft_compat/sections/.text.unlikely
/sys/module/nft_compat/sections/.retpoline_sites
/sys/module/nft_compat/sections/.rodata.str1.8
/sys/module/overlay/notes/.note.Linux
/sys/module/overlay/notes/.note.gnu.build-id
/sys/module/overlay/sections/.data.once
/sys/module/overlay/sections/.note.Linux
/sys/module/overlay/sections/.static_call_sites
/sys/module/overlay/sections/.strtab
/sys/module/overlay/sections/.exit.text
/sys/module/overlay/sections/.exit.data
/sys/module/overlay/sections/.bss
/sys/module/overlay/sections/.return_sites
/sys/module/overlay/sections/.gnu.linkonce.this_module
/sys/module/overlay/sections/.symtab
/sys/module/overlay/sections/.rodata
/sys/module/overlay/sections/.init.text
/sys/module/overlay/sections/.note.gnu.build-id
/sys/module/overlay/sections/.text
/sys/module/overlay/sections/.init.data
/sys/module/overlay/sections/.call_sites
/sys/module/overlay/sections/.data
/sys/module/overlay/sections/.smp_locks
/sys/module/overlay/sections/.rodata.str1.1
/sys/module/overlay/sections/.text.unlikely
/sys/module/overlay/sections/.retpoline_sites
/sys/module/overlay/sections/.rodata.str1.8
/sys/module/dmi_sysfs/notes/.note.Linux
/sys/module/dmi_sysfs/notes/.note.gnu.build-id
/sys/module/dmi_sysfs/sections/.note.Linux
/sys/module/dmi_sysfs/sections/.strtab
/sys/module/dmi_sysfs/sections/.exit.text
/sys/module/dmi_sysfs/sections/.exit.data
/sys/module/dmi_sysfs/sections/.bss
/sys/module/dmi_sysfs/sections/.return_sites
/sys/module/dmi_sysfs/sections/.gnu.linkonce.this_module
/sys/module/dmi_sysfs/sections/.symtab
/sys/module/dmi_sysfs/sections/.rodata
/sys/module/dmi_sysfs/sections/.init.text
/sys/module/dmi_sysfs/sections/.note.gnu.build-id
/sys/module/dmi_sysfs/sections/.text
/sys/module/dmi_sysfs/sections/.init.data
/sys/module/dmi_sysfs/sections/.call_sites
/sys/module/dmi_sysfs/sections/.data
/sys/module/dmi_sysfs/sections/.rodata.str1.1
/sys/module/dmi_sysfs/sections/.retpoline_sites
/sys/module/dmi_sysfs/sections/.rodata.str1.8
/sys/module/algif_hash/notes/.note.Linux
/sys/module/algif_hash/notes/.note.gnu.build-id
/sys/module/algif_hash/sections/.note.Linux
/sys/module/algif_hash/sections/.strtab
/sys/module/algif_hash/sections/.exit.text
/sys/module/algif_hash/sections/.exit.data
/sys/module/algif_hash/sections/.return_sites
/sys/module/algif_hash/sections/.gnu.linkonce.this_module
/sys/module/algif_hash/sections/.symtab
/sys/module/algif_hash/sections/.rodata
/sys/module/algif_hash/sections/.init.text
/sys/module/algif_hash/sections/.note.gnu.build-id
/sys/module/algif_hash/sections/.text
/sys/module/algif_hash/sections/.init.data
/sys/module/algif_hash/sections/.call_sites
/sys/module/algif_hash/sections/.data
/sys/module/algif_hash/sections/.smp_locks
/sys/module/algif_hash/sections/.rodata.str1.1
/sys/module/algif_hash/sections/.text.unlikely
/sys/module/algif_hash/sections/.rodata.str1.8
/sys/module/virtio_dma_buf/notes/.note.Linux
/sys/module/virtio_dma_buf/notes/.note.gnu.build-id
/sys/module/virtio_dma_buf/sections/.note.Linux
/sys/module/virtio_dma_buf/sections/.strtab
/sys/module/virtio_dma_buf/sections/.return_sites
/sys/module/virtio_dma_buf/sections/.gnu.linkonce.this_module
/sys/module/virtio_dma_buf/sections/.symtab
/sys/module/virtio_dma_buf/sections/.note.gnu.build-id
/sys/module/virtio_dma_buf/sections/.text
/sys/module/virtio_dma_buf/sections/.call_sites
/sys/module/virtio_dma_buf/sections/.retpoline_sites
/sys/module/nf_defrag_ipv6/notes/.note.Linux
/sys/module/nf_defrag_ipv6/notes/.note.gnu.build-id
/sys/module/nf_defrag_ipv6/sections/.data..read_mostly
/sys/module/nf_defrag_ipv6/sections/.note.Linux
/sys/module/nf_defrag_ipv6/sections/.strtab
/sys/module/nf_defrag_ipv6/sections/.exit.text
/sys/module/nf_defrag_ipv6/sections/.exit.data
/sys/module/nf_defrag_ipv6/sections/.bss
/sys/module/nf_defrag_ipv6/sections/.return_sites
/sys/module/nf_defrag_ipv6/sections/.gnu.linkonce.this_module
/sys/module/nf_defrag_ipv6/sections/.symtab
/sys/module/nf_defrag_ipv6/sections/.rodata
/sys/module/nf_defrag_ipv6/sections/.init.text
/sys/module/nf_defrag_ipv6/sections/.note.gnu.build-id
/sys/module/nf_defrag_ipv6/sections/.text
/sys/module/nf_defrag_ipv6/sections/.init.data
/sys/module/nf_defrag_ipv6/sections/.call_sites
/sys/module/nf_defrag_ipv6/sections/.data
/sys/module/nf_defrag_ipv6/sections/.smp_locks
/sys/module/nf_defrag_ipv6/sections/.rodata.str1.1
/sys/module/nf_defrag_ipv6/sections/.text.unlikely
/sys/module/nf_defrag_ipv6/sections/.retpoline_sites
/sys/module/nf_defrag_ipv6/sections/.rodata.str1.8
/sys/module/usbhid/notes/.note.Linux
/sys/module/usbhid/notes/.note.gnu.build-id
/sys/module/usbhid/sections/.note.Linux
/sys/module/usbhid/sections/.static_call_sites
/sys/module/usbhid/sections/.strtab
/sys/module/usbhid/sections/.exit.text
/sys/module/usbhid/sections/.exit.data
/sys/module/usbhid/sections/.bss
/sys/module/usbhid/sections/.return_sites
/sys/module/usbhid/sections/.gnu.linkonce.this_module
/sys/module/usbhid/sections/.symtab
/sys/module/usbhid/sections/.rodata
/sys/module/usbhid/sections/.init.text
/sys/module/usbhid/sections/.note.gnu.build-id
/sys/module/usbhid/sections/.text
/sys/module/usbhid/sections/.init.data
/sys/module/usbhid/sections/.call_sites
/sys/module/usbhid/sections/.data
/sys/module/usbhid/sections/.smp_locks
/sys/module/usbhid/sections/.rodata.str1.1
/sys/module/usbhid/sections/.text.unlikely
/sys/module/usbhid/sections/.retpoline_sites
/sys/module/usbhid/sections/.rodata.str1.8
/sys/module/ahci/notes/.note.Linux
/sys/module/ahci/notes/.note.gnu.build-id
/sys/module/ahci/sections/.note.Linux
/sys/module/ahci/sections/.strtab
/sys/module/ahci/sections/.exit.text
/sys/module/ahci/sections/.exit.data
/sys/module/ahci/sections/.bss
/sys/module/ahci/sections/.return_sites
/sys/module/ahci/sections/.gnu.linkonce.this_module
/sys/module/ahci/sections/.symtab
/sys/module/ahci/sections/.rodata
/sys/module/ahci/sections/.init.text
/sys/module/ahci/sections/.note.gnu.build-id
/sys/module/ahci/sections/.text
/sys/module/ahci/sections/.init.data
/sys/module/ahci/sections/.call_sites
/sys/module/ahci/sections/.data
/sys/module/ahci/sections/.smp_locks
/sys/module/ahci/sections/.rodata.str1.1
/sys/module/ahci/sections/.text.unlikely
/sys/module/ahci/sections/.retpoline_sites
/sys/module/ahci/sections/.rodata.str1.8
/sys/module/veth/notes/.note.Linux
/sys/module/veth/notes/.note.gnu.build-id
/sys/module/veth/sections/.note.Linux
/sys/module/veth/sections/.static_call_sites
/sys/module/veth/sections/.strtab
/sys/module/veth/sections/.exit.text
/sys/module/veth/sections/.exit.data
/sys/module/veth/sections/.return_sites
/sys/module/veth/sections/.gnu.linkonce.this_module
/sys/module/veth/sections/.symtab
/sys/module/veth/sections/.rodata
/sys/module/veth/sections/.init.text
/sys/module/veth/sections/.note.gnu.build-id
/sys/module/veth/sections/.text
/sys/module/veth/sections/.init.data
/sys/module/veth/sections/.call_sites
/sys/module/veth/sections/.data
/sys/module/veth/sections/.smp_locks
/sys/module/veth/sections/.rodata.str1.1
/sys/module/veth/sections/.text.unlikely
/sys/module/veth/sections/.retpoline_sites
/sys/module/veth/sections/.rodata.str1.8
/sys/module/qemu_fw_cfg/notes/.note.Linux
/sys/module/qemu_fw_cfg/notes/.note.gnu.build-id
/sys/module/qemu_fw_cfg/sections/.note.Linux
/sys/module/qemu_fw_cfg/sections/.strtab
/sys/module/qemu_fw_cfg/sections/.exit.text
/sys/module/qemu_fw_cfg/sections/.exit.data
/sys/module/qemu_fw_cfg/sections/.bss
/sys/module/qemu_fw_cfg/sections/.return_sites
/sys/module/qemu_fw_cfg/sections/.gnu.linkonce.this_module
/sys/module/qemu_fw_cfg/sections/.symtab
/sys/module/qemu_fw_cfg/sections/.rodata
/sys/module/qemu_fw_cfg/sections/.init.text
/sys/module/qemu_fw_cfg/sections/.note.gnu.build-id
/sys/module/qemu_fw_cfg/sections/.text
/sys/module/qemu_fw_cfg/sections/.init.data
/sys/module/qemu_fw_cfg/sections/.call_sites
/sys/module/qemu_fw_cfg/sections/.data
/sys/module/qemu_fw_cfg/sections/.rodata.str1.1
/sys/module/qemu_fw_cfg/sections/.text.unlikely
/sys/module/qemu_fw_cfg/sections/.retpoline_sites
/sys/module/qemu_fw_cfg/sections/.rodata.str1.8
/sys/module/sha1_ssse3/notes/.note.Linux
/sys/module/sha1_ssse3/notes/.note.gnu.build-id
/sys/module/sha1_ssse3/sections/.rodata.cst16.PSHUFFLE_BYTE_FLIP_MASK
/sys/module/sha1_ssse3/sections/.data.once
/sys/module/sha1_ssse3/sections/.rodata.cst16.UPPER_WORD_MASK
/sys/module/sha1_ssse3/sections/.note.Linux
/sys/module/sha1_ssse3/sections/.strtab
/sys/module/sha1_ssse3/sections/.exit.text
/sys/module/sha1_ssse3/sections/.exit.data
/sys/module/sha1_ssse3/sections/.return_sites
/sys/module/sha1_ssse3/sections/.gnu.linkonce.this_module
/sys/module/sha1_ssse3/sections/.symtab
/sys/module/sha1_ssse3/sections/.rodata
/sys/module/sha1_ssse3/sections/.init.text
/sys/module/sha1_ssse3/sections/.note.gnu.build-id
/sys/module/sha1_ssse3/sections/.text
/sys/module/sha1_ssse3/sections/.init.data
/sys/module/sha1_ssse3/sections/.call_sites
/sys/module/sha1_ssse3/sections/.data
/sys/module/sha1_ssse3/sections/.rodata.str1.1
/sys/module/sha1_ssse3/sections/.text.unlikely
/sys/module/sha1_ssse3/sections/.retpoline_sites
/sys/module/sha1_ssse3/sections/.rodata.str1.8
/sys/module/mptcp_diag/notes/.note.Linux
/sys/module/mptcp_diag/notes/.note.gnu.build-id
/sys/module/mptcp_diag/sections/.note.Linux
/sys/module/mptcp_diag/sections/.static_call_sites
/sys/module/mptcp_diag/sections/.strtab
/sys/module/mptcp_diag/sections/.exit.text
/sys/module/mptcp_diag/sections/.exit.data
/sys/module/mptcp_diag/sections/.return_sites
/sys/module/mptcp_diag/sections/.gnu.linkonce.this_module
/sys/module/mptcp_diag/sections/.symtab
/sys/module/mptcp_diag/sections/.rodata
/sys/module/mptcp_diag/sections/.init.text
/sys/module/mptcp_diag/sections/.note.gnu.build-id
/sys/module/mptcp_diag/sections/.text
/sys/module/mptcp_diag/sections/.init.data
/sys/module/mptcp_diag/sections/.call_sites
/sys/module/mptcp_diag/sections/.data
/sys/module/mptcp_diag/sections/.smp_locks
/sys/module/mptcp_diag/sections/.rodata.str1.1
/sys/module/mptcp_diag/sections/.text.unlikely
/sys/module/mptcp_diag/sections/.rodata.str1.8
/sys/module/xhci_pci_renesas/notes/.note.Linux
/sys/module/xhci_pci_renesas/notes/.note.gnu.build-id
/sys/module/xhci_pci_renesas/sections/.note.Linux
/sys/module/xhci_pci_renesas/sections/.strtab
/sys/module/xhci_pci_renesas/sections/.return_sites
/sys/module/xhci_pci_renesas/sections/.gnu.linkonce.this_module
/sys/module/xhci_pci_renesas/sections/.symtab
/sys/module/xhci_pci_renesas/sections/.rodata
/sys/module/xhci_pci_renesas/sections/.note.gnu.build-id
/sys/module/xhci_pci_renesas/sections/.text
/sys/module/xhci_pci_renesas/sections/.call_sites
/sys/module/xhci_pci_renesas/sections/.rodata.str1.1
/sys/module/xhci_pci_renesas/sections/.rodata.str1.8
/sys/module/dm_multipath/notes/.note.Linux
/sys/module/dm_multipath/notes/.note.gnu.build-id
/sys/module/dm_multipath/sections/.data.once
/sys/module/dm_multipath/sections/.note.Linux
/sys/module/dm_multipath/sections/.strtab
/sys/module/dm_multipath/sections/.exit.text
/sys/module/dm_multipath/sections/.exit.data
/sys/module/dm_multipath/sections/.bss
/sys/module/dm_multipath/sections/.return_sites
/sys/module/dm_multipath/sections/.gnu.linkonce.this_module
/sys/module/dm_multipath/sections/.symtab
/sys/module/dm_multipath/sections/.rodata
/sys/module/dm_multipath/sections/.init.text
/sys/module/dm_multipath/sections/.note.gnu.build-id
/sys/module/dm_multipath/sections/.text
/sys/module/dm_multipath/sections/.init.data
/sys/module/dm_multipath/sections/.call_sites
/sys/module/dm_multipath/sections/.data
/sys/module/dm_multipath/sections/.smp_locks
/sys/module/dm_multipath/sections/.rodata.str1.1
/sys/module/dm_multipath/sections/.text.unlikely
/sys/module/dm_multipath/sections/.retpoline_sites
/sys/module/dm_multipath/sections/.rodata.str1.8
/sys/module/xsk_diag/notes/.note.Linux
/sys/module/xsk_diag/notes/.note.gnu.build-id
/sys/module/xsk_diag/sections/.note.Linux
/sys/module/xsk_diag/sections/.strtab
/sys/module/xsk_diag/sections/.exit.text
/sys/module/xsk_diag/sections/.exit.data
/sys/module/xsk_diag/sections/.return_sites
/sys/module/xsk_diag/sections/.gnu.linkonce.this_module
/sys/module/xsk_diag/sections/.symtab
/sys/module/xsk_diag/sections/.rodata
/sys/module/xsk_diag/sections/.init.text
/sys/module/xsk_diag/sections/.note.gnu.build-id
/sys/module/xsk_diag/sections/.text
/sys/module/xsk_diag/sections/.init.data
/sys/module/xsk_diag/sections/.call_sites
/sys/module/xsk_diag/sections/.data
/sys/module/xsk_diag/sections/.rodata.str1.1
/sys/module/xsk_diag/sections/.text.unlikely
/sys/module/xsk_diag/sections/.rodata.str1.8
/sys/module/xt_addrtype/notes/.note.Linux
/sys/module/xt_addrtype/notes/.note.gnu.build-id
/sys/module/xt_addrtype/sections/.data..read_mostly
/sys/module/xt_addrtype/sections/.note.Linux
/sys/module/xt_addrtype/sections/.strtab
/sys/module/xt_addrtype/sections/.exit.text
/sys/module/xt_addrtype/sections/.exit.data
/sys/module/xt_addrtype/sections/.return_sites
/sys/module/xt_addrtype/sections/.gnu.linkonce.this_module
/sys/module/xt_addrtype/sections/.symtab
/sys/module/xt_addrtype/sections/.rodata
/sys/module/xt_addrtype/sections/.init.text
/sys/module/xt_addrtype/sections/.note.gnu.build-id
/sys/module/xt_addrtype/sections/.text
/sys/module/xt_addrtype/sections/.init.data
/sys/module/xt_addrtype/sections/.call_sites
/sys/module/xt_addrtype/sections/.data
/sys/module/xt_addrtype/sections/.rodata.str1.1
/sys/module/xt_addrtype/sections/.text.unlikely
/sys/module/xt_addrtype/sections/.rodata.str1.8
/sys/module/mac_hid/notes/.note.Linux
/sys/module/mac_hid/notes/.note.gnu.build-id
/sys/module/mac_hid/sections/.note.Linux
/sys/module/mac_hid/sections/.strtab
/sys/module/mac_hid/sections/.exit.text
/sys/module/mac_hid/sections/.exit.data
/sys/module/mac_hid/sections/.bss
/sys/module/mac_hid/sections/.return_sites
/sys/module/mac_hid/sections/.gnu.linkonce.this_module
/sys/module/mac_hid/sections/.symtab
/sys/module/mac_hid/sections/.rodata
/sys/module/mac_hid/sections/.init.text
/sys/module/mac_hid/sections/.note.gnu.build-id
/sys/module/mac_hid/sections/.text
/sys/module/mac_hid/sections/.init.data
/sys/module/mac_hid/sections/.call_sites
/sys/module/mac_hid/sections/.data
/sys/module/mac_hid/sections/.rodata.str1.1
/sys/module/mac_hid/sections/.rodata.str1.8
/sys/module/blake2b_generic/notes/.note.Linux
/sys/module/blake2b_generic/notes/.note.gnu.build-id
/sys/module/blake2b_generic/sections/.data.once
/sys/module/blake2b_generic/sections/.note.Linux
/sys/module/blake2b_generic/sections/.strtab
/sys/module/blake2b_generic/sections/.exit.text
/sys/module/blake2b_generic/sections/.exit.data
/sys/module/blake2b_generic/sections/.return_sites
/sys/module/blake2b_generic/sections/.gnu.linkonce.this_module
/sys/module/blake2b_generic/sections/.symtab
/sys/module/blake2b_generic/sections/.init.text
/sys/module/blake2b_generic/sections/.note.gnu.build-id
/sys/module/blake2b_generic/sections/.text
/sys/module/blake2b_generic/sections/.init.data
/sys/module/blake2b_generic/sections/.call_sites
/sys/module/blake2b_generic/sections/.data
/sys/module/blake2b_generic/sections/.rodata.str1.1
/sys/module/blake2b_generic/sections/.text.unlikely
/sys/module/blake2b_generic/sections/.rodata.str1.8
/sys/module/raid6_pq/notes/.note.Linux
/sys/module/raid6_pq/notes/.note.gnu.build-id
/sys/module/raid6_pq/sections/.note.Linux
/sys/module/raid6_pq/sections/.static_call_sites
/sys/module/raid6_pq/sections/.strtab
/sys/module/raid6_pq/sections/.exit.data
/sys/module/raid6_pq/sections/.bss
/sys/module/raid6_pq/sections/.return_sites
/sys/module/raid6_pq/sections/.gnu.linkonce.this_module
/sys/module/raid6_pq/sections/.symtab
/sys/module/raid6_pq/sections/.rodata
/sys/module/raid6_pq/sections/.init.text
/sys/module/raid6_pq/sections/.note.gnu.build-id
/sys/module/raid6_pq/sections/.text
/sys/module/raid6_pq/sections/.init.data
/sys/module/raid6_pq/sections/.call_sites
/sys/module/raid6_pq/sections/.data
/sys/module/raid6_pq/sections/.rodata.str1.1
/sys/module/raid6_pq/sections/.retpoline_sites
/sys/module/raid6_pq/sections/.rodata.str1.8
/sys/module/nf_defrag_ipv4/notes/.note.Linux
/sys/module/nf_defrag_ipv4/notes/.note.gnu.build-id
/sys/module/nf_defrag_ipv4/sections/.note.Linux
/sys/module/nf_defrag_ipv4/sections/.strtab
/sys/module/nf_defrag_ipv4/sections/.exit.text
/sys/module/nf_defrag_ipv4/sections/.exit.data
/sys/module/nf_defrag_ipv4/sections/.return_sites
/sys/module/nf_defrag_ipv4/sections/.gnu.linkonce.this_module
/sys/module/nf_defrag_ipv4/sections/.symtab
/sys/module/nf_defrag_ipv4/sections/.rodata
/sys/module/nf_defrag_ipv4/sections/.init.text
/sys/module/nf_defrag_ipv4/sections/.note.gnu.build-id
/sys/module/nf_defrag_ipv4/sections/.text
/sys/module/nf_defrag_ipv4/sections/.init.data
/sys/module/nf_defrag_ipv4/sections/.call_sites
/sys/module/nf_defrag_ipv4/sections/.data
/sys/module/nf_defrag_ipv4/sections/.text.unlikely
/sys/module/nf_defrag_ipv4/sections/.rodata.str1.8
/sys/module/raw_diag/notes/.note.Linux
/sys/module/raw_diag/notes/.note.gnu.build-id
/sys/module/raw_diag/sections/.note.Linux
/sys/module/raw_diag/sections/.strtab
/sys/module/raw_diag/sections/.exit.text
/sys/module/raw_diag/sections/.exit.data
/sys/module/raw_diag/sections/.return_sites
/sys/module/raw_diag/sections/.gnu.linkonce.this_module
/sys/module/raw_diag/sections/.symtab
/sys/module/raw_diag/sections/.rodata
/sys/module/raw_diag/sections/.init.text
/sys/module/raw_diag/sections/.note.gnu.build-id
/sys/module/raw_diag/sections/.text
/sys/module/raw_diag/sections/.init.data
/sys/module/raw_diag/sections/.call_sites
/sys/module/raw_diag/sections/.data
/sys/module/raw_diag/sections/.smp_locks
/sys/module/raw_diag/sections/.rodata.str1.8
/sys/module/intel_rapl_msr/notes/.note.Linux
/sys/module/intel_rapl_msr/notes/.note.gnu.build-id
/sys/module/intel_rapl_msr/sections/.altinstructions
/sys/module/intel_rapl_msr/sections/.note.Linux
/sys/module/intel_rapl_msr/sections/.strtab
/sys/module/intel_rapl_msr/sections/.exit.text
/sys/module/intel_rapl_msr/sections/.exit.data
/sys/module/intel_rapl_msr/sections/.bss
/sys/module/intel_rapl_msr/sections/.return_sites
/sys/module/intel_rapl_msr/sections/.gnu.linkonce.this_module
/sys/module/intel_rapl_msr/sections/.symtab
/sys/module/intel_rapl_msr/sections/.rodata
/sys/module/intel_rapl_msr/sections/.init.text
/sys/module/intel_rapl_msr/sections/.note.gnu.build-id
/sys/module/intel_rapl_msr/sections/.text
/sys/module/intel_rapl_msr/sections/.init.data
/sys/module/intel_rapl_msr/sections/.call_sites
/sys/module/intel_rapl_msr/sections/.data
/sys/module/intel_rapl_msr/sections/.altinstr_replacement
/sys/module/intel_rapl_msr/sections/.smp_locks
/sys/module/intel_rapl_msr/sections/.rodata.str1.1
/sys/module/intel_rapl_msr/sections/.rodata.str1.8
/sys/module/libcrc32c/notes/.note.Linux
/sys/module/libcrc32c/notes/.note.gnu.build-id
/sys/module/libcrc32c/sections/.note.Linux
/sys/module/libcrc32c/sections/.strtab
/sys/module/libcrc32c/sections/.exit.text
/sys/module/libcrc32c/sections/.exit.data
/sys/module/libcrc32c/sections/.bss
/sys/module/libcrc32c/sections/.return_sites
/sys/module/libcrc32c/sections/.gnu.linkonce.this_module
/sys/module/libcrc32c/sections/.symtab
/sys/module/libcrc32c/sections/.init.text
/sys/module/libcrc32c/sections/.note.gnu.build-id
/sys/module/libcrc32c/sections/.text
/sys/module/libcrc32c/sections/.init.data
/sys/module/libcrc32c/sections/.call_sites
/sys/module/libcrc32c/sections/.rodata.str1.1
/sys/module/intel_uncore_frequency_common/notes/.note.Linux
/sys/module/intel_uncore_frequency_common/notes/.note.gnu.build-id
/sys/module/intel_uncore_frequency_common/sections/.note.Linux
/sys/module/intel_uncore_frequency_common/sections/.strtab
/sys/module/intel_uncore_frequency_common/sections/.bss
/sys/module/intel_uncore_frequency_common/sections/.return_sites
/sys/module/intel_uncore_frequency_common/sections/.gnu.linkonce.this_module
/sys/module/intel_uncore_frequency_common/sections/.symtab
/sys/module/intel_uncore_frequency_common/sections/.note.gnu.build-id
/sys/module/intel_uncore_frequency_common/sections/.text
/sys/module/intel_uncore_frequency_common/sections/.call_sites
/sys/module/intel_uncore_frequency_common/sections/.data
/sys/module/intel_uncore_frequency_common/sections/.rodata.str1.1
/sys/module/intel_uncore_frequency_common/sections/.text.unlikely
/sys/module/intel_uncore_frequency_common/sections/.retpoline_sites
/sys/module/intel_uncore_frequency_common/sections/.rodata.str1.8
/sys/module/raid10/notes/.note.Linux
/sys/module/raid10/notes/.note.gnu.build-id
/sys/module/raid10/sections/.note.Linux
/sys/module/raid10/sections/.static_call_sites
/sys/module/raid10/sections/.strtab
/sys/module/raid10/sections/.exit.data
/sys/module/raid10/sections/.return_sites
/sys/module/raid10/sections/.gnu.linkonce.this_module
/sys/module/raid10/sections/.symtab
/sys/module/raid10/sections/.rodata
/sys/module/raid10/sections/.init.text
/sys/module/raid10/sections/.note.gnu.build-id
/sys/module/raid10/sections/.text
/sys/module/raid10/sections/.init.data
/sys/module/raid10/sections/.call_sites
/sys/module/raid10/sections/.data
/sys/module/raid10/sections/.smp_locks
/sys/module/raid10/sections/.rodata.str1.1
/sys/module/raid10/sections/.text.unlikely
/sys/module/raid10/sections/.retpoline_sites
/sys/module/raid10/sections/.rodata.str1.8
/sys/module/xfrm_algo/notes/.note.Linux
/sys/module/xfrm_algo/notes/.note.gnu.build-id
/sys/module/xfrm_algo/sections/.note.Linux
/sys/module/xfrm_algo/sections/.strtab
/sys/module/xfrm_algo/sections/.return_sites
/sys/module/xfrm_algo/sections/.gnu.linkonce.this_module
/sys/module/xfrm_algo/sections/.symtab
/sys/module/xfrm_algo/sections/.note.gnu.build-id
/sys/module/xfrm_algo/sections/.text
/sys/module/xfrm_algo/sections/.call_sites
/sys/module/xfrm_algo/sections/.data
/sys/module/xfrm_algo/sections/.rodata.str1.1
/sys/module/xfrm_algo/sections/.rodata.str1.8
/sys/module/udp_diag/notes/.note.Linux
/sys/module/udp_diag/notes/.note.gnu.build-id
/sys/module/udp_diag/sections/.note.Linux
/sys/module/udp_diag/sections/.strtab
/sys/module/udp_diag/sections/.exit.text
/sys/module/udp_diag/sections/.exit.data
/sys/module/udp_diag/sections/.return_sites
/sys/module/udp_diag/sections/.gnu.linkonce.this_module
/sys/module/udp_diag/sections/.symtab
/sys/module/udp_diag/sections/.rodata
/sys/module/udp_diag/sections/.init.text
/sys/module/udp_diag/sections/.note.gnu.build-id
/sys/module/udp_diag/sections/.text
/sys/module/udp_diag/sections/.init.data
/sys/module/udp_diag/sections/.call_sites
/sys/module/udp_diag/sections/.data
/sys/module/udp_diag/sections/.smp_locks
/sys/module/udp_diag/sections/.rodata.str1.1
/sys/module/udp_diag/sections/.text.unlikely
/sys/module/udp_diag/sections/.rodata.str1.8
/sys/module/serio_raw/notes/.note.Linux
/sys/module/serio_raw/notes/.note.gnu.build-id
/sys/module/serio_raw/sections/.note.Linux
/sys/module/serio_raw/sections/.static_call_sites
/sys/module/serio_raw/sections/.strtab
/sys/module/serio_raw/sections/.exit.text
/sys/module/serio_raw/sections/.exit.data
/sys/module/serio_raw/sections/.return_sites
/sys/module/serio_raw/sections/.gnu.linkonce.this_module
/sys/module/serio_raw/sections/.symtab
/sys/module/serio_raw/sections/.rodata
/sys/module/serio_raw/sections/.init.text
/sys/module/serio_raw/sections/.note.gnu.build-id
/sys/module/serio_raw/sections/.text
/sys/module/serio_raw/sections/.init.data
/sys/module/serio_raw/sections/.call_sites
/sys/module/serio_raw/sections/.data
/sys/module/serio_raw/sections/.smp_locks
/sys/module/serio_raw/sections/.rodata.str1.1
/sys/module/serio_raw/sections/.text.unlikely
/sys/module/serio_raw/sections/.retpoline_sites
/sys/module/serio_raw/sections/.rodata.str1.8
/sys/module/hid/notes/.note.Linux
/sys/module/hid/notes/.note.gnu.build-id
/sys/module/hid/sections/.data..read_mostly
/sys/module/hid/sections/.note.Linux
/sys/module/hid/sections/.strtab
/sys/module/hid/sections/.exit.text
/sys/module/hid/sections/.exit.data
/sys/module/hid/sections/.bss
/sys/module/hid/sections/.return_sites
/sys/module/hid/sections/.gnu.linkonce.this_module
/sys/module/hid/sections/.symtab
/sys/module/hid/sections/.rodata
/sys/module/hid/sections/.init.text
/sys/module/hid/sections/.note.gnu.build-id
/sys/module/hid/sections/.text
/sys/module/hid/sections/.init.data
/sys/module/hid/sections/.call_sites
/sys/module/hid/sections/.data
/sys/module/hid/sections/.smp_locks
/sys/module/hid/sections/.rodata.str1.1
/sys/module/hid/sections/.text.unlikely
/sys/module/hid/sections/.retpoline_sites
/sys/module/hid/sections/.rodata.str1.8
/sys/module/polyval_generic/notes/.note.Linux
/sys/module/polyval_generic/notes/.note.gnu.build-id
/sys/module/polyval_generic/sections/.note.Linux
/sys/module/polyval_generic/sections/.strtab
/sys/module/polyval_generic/sections/.exit.text
/sys/module/polyval_generic/sections/.exit.data
/sys/module/polyval_generic/sections/.return_sites
/sys/module/polyval_generic/sections/.gnu.linkonce.this_module
/sys/module/polyval_generic/sections/.symtab
/sys/module/polyval_generic/sections/.init.text
/sys/module/polyval_generic/sections/.note.gnu.build-id
/sys/module/polyval_generic/sections/.text
/sys/module/polyval_generic/sections/.init.data
/sys/module/polyval_generic/sections/.call_sites
/sys/module/polyval_generic/sections/.data
/sys/module/ghash_clmulni_intel/notes/.note.Linux
/sys/module/ghash_clmulni_intel/notes/.note.gnu.build-id
/sys/module/ghash_clmulni_intel/sections/.note.Linux
/sys/module/ghash_clmulni_intel/sections/.strtab
/sys/module/ghash_clmulni_intel/sections/.exit.text
/sys/module/ghash_clmulni_intel/sections/.exit.data
/sys/module/ghash_clmulni_intel/sections/.return_sites
/sys/module/ghash_clmulni_intel/sections/.gnu.linkonce.this_module
/sys/module/ghash_clmulni_intel/sections/.symtab
/sys/module/ghash_clmulni_intel/sections/.rodata
/sys/module/ghash_clmulni_intel/sections/.init.text
/sys/module/ghash_clmulni_intel/sections/.note.gnu.build-id
/sys/module/ghash_clmulni_intel/sections/.text
/sys/module/ghash_clmulni_intel/sections/.rodata.cst16.bswap_mask
/sys/module/ghash_clmulni_intel/sections/.init.data
/sys/module/ghash_clmulni_intel/sections/.call_sites
/sys/module/ghash_clmulni_intel/sections/.data
/sys/module/ghash_clmulni_intel/sections/.rodata.str1.1
/sys/module/ghash_clmulni_intel/sections/.retpoline_sites
/sys/module/joydev/notes/.note.Linux
/sys/module/joydev/notes/.note.gnu.build-id
/sys/module/joydev/sections/.note.Linux
/sys/module/joydev/sections/.static_call_sites
/sys/module/joydev/sections/.strtab
/sys/module/joydev/sections/.exit.text
/sys/module/joydev/sections/.exit.data
/sys/module/joydev/sections/.return_sites
/sys/module/joydev/sections/.gnu.linkonce.this_module
/sys/module/joydev/sections/.symtab
/sys/module/joydev/sections/.rodata
/sys/module/joydev/sections/.init.text
/sys/module/joydev/sections/.note.gnu.build-id
/sys/module/joydev/sections/.text
/sys/module/joydev/sections/.init.data
/sys/module/joydev/sections/.call_sites
/sys/module/joydev/sections/.data
/sys/module/joydev/sections/.rodata.str1.1
/sys/module/joydev/sections/.text.unlikely
/sys/module/joydev/sections/.retpoline_sites
/sys/module/joydev/sections/.rodata.str1.8
/sys/module/af_alg/notes/.note.Linux
/sys/module/af_alg/notes/.note.gnu.build-id
/sys/module/af_alg/sections/.data.once
/sys/module/af_alg/sections/.note.Linux
/sys/module/af_alg/sections/.strtab
/sys/module/af_alg/sections/.exit.text
/sys/module/af_alg/sections/.exit.data
/sys/module/af_alg/sections/.return_sites
/sys/module/af_alg/sections/.gnu.linkonce.this_module
/sys/module/af_alg/sections/.symtab
/sys/module/af_alg/sections/.rodata
/sys/module/af_alg/sections/.init.text
/sys/module/af_alg/sections/.note.gnu.build-id
/sys/module/af_alg/sections/.text
/sys/module/af_alg/sections/.init.data
/sys/module/af_alg/sections/.call_sites
/sys/module/af_alg/sections/.data
/sys/module/af_alg/sections/.smp_locks
/sys/module/af_alg/sections/.rodata.str1.1
/sys/module/af_alg/sections/.text.unlikely
/sys/module/af_alg/sections/.retpoline_sites
/sys/module/af_alg/sections/.rodata.str1.8
/sys/module/raid0/notes/.note.Linux
/sys/module/raid0/notes/.note.gnu.build-id
/sys/module/raid0/sections/.data.once
/sys/module/raid0/sections/.note.Linux
/sys/module/raid0/sections/.static_call_sites
/sys/module/raid0/sections/.strtab
/sys/module/raid0/sections/.exit.data
/sys/module/raid0/sections/.bss
/sys/module/raid0/sections/.return_sites
/sys/module/raid0/sections/.gnu.linkonce.this_module
/sys/module/raid0/sections/.symtab
/sys/module/raid0/sections/.rodata
/sys/module/raid0/sections/.init.text
/sys/module/raid0/sections/.note.gnu.build-id
/sys/module/raid0/sections/.text
/sys/module/raid0/sections/.init.data
/sys/module/raid0/sections/.call_sites
/sys/module/raid0/sections/.data
/sys/module/raid0/sections/.smp_locks
/sys/module/raid0/sections/.rodata.str1.1
/sys/module/raid0/sections/.text.unlikely
/sys/module/raid0/sections/.rodata.str1.8
/sys/module/lpc_ich/notes/.note.Linux
/sys/module/lpc_ich/notes/.note.gnu.build-id
/sys/module/lpc_ich/sections/.note.Linux
/sys/module/lpc_ich/sections/.strtab
/sys/module/lpc_ich/sections/.exit.text
/sys/module/lpc_ich/sections/.exit.data
/sys/module/lpc_ich/sections/.return_sites
/sys/module/lpc_ich/sections/.gnu.linkonce.this_module
/sys/module/lpc_ich/sections/.symtab
/sys/module/lpc_ich/sections/.rodata
/sys/module/lpc_ich/sections/.init.text
/sys/module/lpc_ich/sections/.note.gnu.build-id
/sys/module/lpc_ich/sections/.text
/sys/module/lpc_ich/sections/.init.data
/sys/module/lpc_ich/sections/.call_sites
/sys/module/lpc_ich/sections/.data
/sys/module/lpc_ich/sections/.rodata.str1.1
/sys/module/lpc_ich/sections/.rodata.str1.8
/sys/module/async_xor/notes/.note.Linux
/sys/module/async_xor/notes/.note.gnu.build-id
/sys/module/async_xor/sections/.data.once
/sys/module/async_xor/sections/.note.Linux
/sys/module/async_xor/sections/.strtab
/sys/module/async_xor/sections/.return_sites
/sys/module/async_xor/sections/.gnu.linkonce.this_module
/sys/module/async_xor/sections/.symtab
/sys/module/async_xor/sections/.rodata
/sys/module/async_xor/sections/.note.gnu.build-id
/sys/module/async_xor/sections/.text
/sys/module/async_xor/sections/.call_sites
/sys/module/async_xor/sections/.data
/sys/module/async_xor/sections/.smp_locks
/sys/module/async_xor/sections/.rodata.str1.1
/sys/module/async_xor/sections/.text.unlikely
/sys/module/async_xor/sections/.retpoline_sites
/sys/module/async_xor/sections/.rodata.str1.8
/sys/module/nls_iso8859_1/notes/.note.Linux
/sys/module/nls_iso8859_1/notes/.note.gnu.build-id
/sys/module/nls_iso8859_1/sections/.note.Linux
/sys/module/nls_iso8859_1/sections/.strtab
/sys/module/nls_iso8859_1/sections/.exit.text
/sys/module/nls_iso8859_1/sections/.exit.data
/sys/module/nls_iso8859_1/sections/.return_sites
/sys/module/nls_iso8859_1/sections/.gnu.linkonce.this_module
/sys/module/nls_iso8859_1/sections/.symtab
/sys/module/nls_iso8859_1/sections/.rodata
/sys/module/nls_iso8859_1/sections/.init.text
/sys/module/nls_iso8859_1/sections/.note.gnu.build-id
/sys/module/nls_iso8859_1/sections/.text
/sys/module/nls_iso8859_1/sections/.init.data
/sys/module/nls_iso8859_1/sections/.call_sites
/sys/module/nls_iso8859_1/sections/.data
/sys/module/nls_iso8859_1/sections/.rodata.str1.1
/sys/module/nls_iso8859_1/sections/.rodata.str1.8
/sys/module/i2c_smbus/notes/.note.Linux
/sys/module/i2c_smbus/notes/.note.gnu.build-id
/sys/module/i2c_smbus/sections/.note.Linux
/sys/module/i2c_smbus/sections/.strtab
/sys/module/i2c_smbus/sections/.exit.text
/sys/module/i2c_smbus/sections/.exit.data
/sys/module/i2c_smbus/sections/.return_sites
/sys/module/i2c_smbus/sections/.gnu.linkonce.this_module
/sys/module/i2c_smbus/sections/.symtab
/sys/module/i2c_smbus/sections/.rodata
/sys/module/i2c_smbus/sections/.init.text
/sys/module/i2c_smbus/sections/.note.gnu.build-id
/sys/module/i2c_smbus/sections/.text
/sys/module/i2c_smbus/sections/.init.data
/sys/module/i2c_smbus/sections/.call_sites
/sys/module/i2c_smbus/sections/.data
/sys/module/i2c_smbus/sections/.rodata.str1.1
/sys/module/i2c_smbus/sections/.retpoline_sites
/sys/module/i2c_smbus/sections/.rodata.str1.8
/sys/module/btrfs/notes/.note.Linux
/sys/module/btrfs/notes/.note.gnu.build-id
/sys/module/btrfs/sections/.altinstructions
/sys/module/btrfs/sections/.data.once
/sys/module/btrfs/sections/.note.Linux
/sys/module/btrfs/sections/.static_call_sites
/sys/module/btrfs/sections/.strtab
/sys/module/btrfs/sections/.exit.text
/sys/module/btrfs/sections/.exit.data
/sys/module/btrfs/sections/.bss
/sys/module/btrfs/sections/.static_call.text
/sys/module/btrfs/sections/.return_sites
/sys/module/btrfs/sections/.gnu.linkonce.this_module
/sys/module/btrfs/sections/.symtab
/sys/module/btrfs/sections/.rodata
/sys/module/btrfs/sections/.init.text
/sys/module/btrfs/sections/.note.gnu.build-id
/sys/module/btrfs/sections/.text
/sys/module/btrfs/sections/.init.data
/sys/module/btrfs/sections/.call_sites
/sys/module/btrfs/sections/.data
/sys/module/btrfs/sections/.altinstr_replacement
/sys/module/btrfs/sections/.smp_locks
/sys/module/btrfs/sections/.rodata.str1.1
/sys/module/btrfs/sections/.text.unlikely
/sys/module/btrfs/sections/.rodata.cst2
/sys/module/btrfs/sections/.retpoline_sites
/sys/module/btrfs/sections/.rodata.str1.8
/sys/module/btrfs/sections/.ref.data
/sys/module/bluetooth/notes/.note.Linux
/sys/module/bluetooth/notes/.note.gnu.build-id
/sys/module/bluetooth/sections/.data.once
/sys/module/bluetooth/sections/.note.Linux
/sys/module/bluetooth/sections/.static_call_sites
/sys/module/bluetooth/sections/.strtab
/sys/module/bluetooth/sections/.exit.text
/sys/module/bluetooth/sections/.exit.data
/sys/module/bluetooth/sections/.bss
/sys/module/bluetooth/sections/.return_sites
/sys/module/bluetooth/sections/.gnu.linkonce.this_module
/sys/module/bluetooth/sections/.symtab
/sys/module/bluetooth/sections/.rodata
/sys/module/bluetooth/sections/.init.text
/sys/module/bluetooth/sections/.note.gnu.build-id
/sys/module/bluetooth/sections/.text
/sys/module/bluetooth/sections/.init.data
/sys/module/bluetooth/sections/.call_sites
/sys/module/bluetooth/sections/.data
/sys/module/bluetooth/sections/.smp_locks
/sys/module/bluetooth/sections/.rodata.str1.1
/sys/module/bluetooth/sections/.text.unlikely
/sys/module/bluetooth/sections/.rodata.cst2
/sys/module/bluetooth/sections/.retpoline_sites
/sys/module/bluetooth/sections/.rodata.str1.8
/sys/module/hid_generic/notes/.note.Linux
/sys/module/hid_generic/notes/.note.gnu.build-id
/sys/module/hid_generic/sections/.note.Linux
/sys/module/hid_generic/sections/.strtab
/sys/module/hid_generic/sections/.exit.text
/sys/module/hid_generic/sections/.exit.data
/sys/module/hid_generic/sections/.return_sites
/sys/module/hid_generic/sections/.gnu.linkonce.this_module
/sys/module/hid_generic/sections/.symtab
/sys/module/hid_generic/sections/.rodata
/sys/module/hid_generic/sections/.init.text
/sys/module/hid_generic/sections/.note.gnu.build-id
/sys/module/hid_generic/sections/.text
/sys/module/hid_generic/sections/.init.data
/sys/module/hid_generic/sections/.call_sites
/sys/module/hid_generic/sections/.data
/sys/module/hid_generic/sections/.rodata.str1.1
/sys/module/autofs4/notes/.note.Linux
/sys/module/autofs4/notes/.note.gnu.build-id
/sys/module/autofs4/sections/.data.once
/sys/module/autofs4/sections/.note.Linux
/sys/module/autofs4/sections/.static_call_sites
/sys/module/autofs4/sections/.strtab
/sys/module/autofs4/sections/.exit.text
/sys/module/autofs4/sections/.exit.data
/sys/module/autofs4/sections/.return_sites
/sys/module/autofs4/sections/.gnu.linkonce.this_module
/sys/module/autofs4/sections/.symtab
/sys/module/autofs4/sections/.rodata
/sys/module/autofs4/sections/.init.text
/sys/module/autofs4/sections/.note.gnu.build-id
/sys/module/autofs4/sections/.text
/sys/module/autofs4/sections/.init.data
/sys/module/autofs4/sections/.call_sites
/sys/module/autofs4/sections/.data
/sys/module/autofs4/sections/.smp_locks
/sys/module/autofs4/sections/.rodata.str1.1
/sys/module/autofs4/sections/.text.unlikely
/sys/module/autofs4/sections/.retpoline_sites
/sys/module/autofs4/sections/.rodata.str1.8
/sys/module/unix_diag/notes/.note.Linux
/sys/module/unix_diag/notes/.note.gnu.build-id
/sys/module/unix_diag/sections/.note.Linux
/sys/module/unix_diag/sections/.strtab
/sys/module/unix_diag/sections/.exit.text
/sys/module/unix_diag/sections/.exit.data
/sys/module/unix_diag/sections/.return_sites
/sys/module/unix_diag/sections/.gnu.linkonce.this_module
/sys/module/unix_diag/sections/.symtab
/sys/module/unix_diag/sections/.rodata
/sys/module/unix_diag/sections/.init.text
/sys/module/unix_diag/sections/.note.gnu.build-id
/sys/module/unix_diag/sections/.text
/sys/module/unix_diag/sections/.init.data
/sys/module/unix_diag/sections/.call_sites
/sys/module/unix_diag/sections/.data
/sys/module/unix_diag/sections/.smp_locks
/sys/module/unix_diag/sections/.rodata.str1.1
/sys/module/unix_diag/sections/.text.unlikely
/sys/module/unix_diag/sections/.rodata.str1.8
/sys/module/netlink_diag/notes/.note.Linux
/sys/module/netlink_diag/notes/.note.gnu.build-id
/sys/module/netlink_diag/sections/.note.Linux
/sys/module/netlink_diag/sections/.strtab
/sys/module/netlink_diag/sections/.exit.text
/sys/module/netlink_diag/sections/.exit.data
/sys/module/netlink_diag/sections/.return_sites
/sys/module/netlink_diag/sections/.gnu.linkonce.this_module
/sys/module/netlink_diag/sections/.symtab
/sys/module/netlink_diag/sections/.rodata
/sys/module/netlink_diag/sections/.init.text
/sys/module/netlink_diag/sections/.note.gnu.build-id
/sys/module/netlink_diag/sections/.text
/sys/module/netlink_diag/sections/.init.data
/sys/module/netlink_diag/sections/.call_sites
/sys/module/netlink_diag/sections/.data
/sys/module/netlink_diag/sections/.rodata.str1.1
/sys/module/netlink_diag/sections/.text.unlikely
/sys/module/netlink_diag/sections/.rodata.str1.8
/sys/module/nf_conntrack_netlink/notes/.note.Linux
/sys/module/nf_conntrack_netlink/notes/.note.gnu.build-id
/sys/module/nf_conntrack_netlink/sections/.data.once
/sys/module/nf_conntrack_netlink/sections/.note.Linux
/sys/module/nf_conntrack_netlink/sections/.strtab
/sys/module/nf_conntrack_netlink/sections/.exit.text
/sys/module/nf_conntrack_netlink/sections/.exit.data
/sys/module/nf_conntrack_netlink/sections/.bss
/sys/module/nf_conntrack_netlink/sections/.return_sites
/sys/module/nf_conntrack_netlink/sections/.gnu.linkonce.this_module
/sys/module/nf_conntrack_netlink/sections/.symtab
/sys/module/nf_conntrack_netlink/sections/.rodata
/sys/module/nf_conntrack_netlink/sections/.init.text
/sys/module/nf_conntrack_netlink/sections/.note.gnu.build-id
/sys/module/nf_conntrack_netlink/sections/.text
/sys/module/nf_conntrack_netlink/sections/.init.data
/sys/module/nf_conntrack_netlink/sections/.call_sites
/sys/module/nf_conntrack_netlink/sections/.data
/sys/module/nf_conntrack_netlink/sections/.smp_locks
/sys/module/nf_conntrack_netlink/sections/.rodata.str1.1
/sys/module/nf_conntrack_netlink/sections/.text.unlikely
/sys/module/nf_conntrack_netlink/sections/.rodata.cst2
/sys/module/nf_conntrack_netlink/sections/.retpoline_sites
/sys/module/nf_conntrack_netlink/sections/.rodata.str1.8
/sys/module/nf_tables/notes/.note.Linux
/sys/module/nf_tables/notes/.note.gnu.build-id
/sys/module/nf_tables/sections/.altinstructions
/sys/module/nf_tables/sections/.data.once
/sys/module/nf_tables/sections/.data..read_mostly
/sys/module/nf_tables/sections/.note.Linux
/sys/module/nf_tables/sections/.static_call_sites
/sys/module/nf_tables/sections/.strtab
/sys/module/nf_tables/sections/.exit.text
/sys/module/nf_tables/sections/.exit.data
/sys/module/nf_tables/sections/.bss
/sys/module/nf_tables/sections/.return_sites
/sys/module/nf_tables/sections/.gnu.linkonce.this_module
/sys/module/nf_tables/sections/.symtab
/sys/module/nf_tables/sections/.rodata
/sys/module/nf_tables/sections/.init.text
/sys/module/nf_tables/sections/.note.gnu.build-id
/sys/module/nf_tables/sections/.text
/sys/module/nf_tables/sections/.init.data
/sys/module/nf_tables/sections/.call_sites
/sys/module/nf_tables/sections/.data
/sys/module/nf_tables/sections/.altinstr_replacement
/sys/module/nf_tables/sections/.smp_locks
/sys/module/nf_tables/sections/.rodata.str1.1
/sys/module/nf_tables/sections/.text.unlikely
/sys/module/nf_tables/sections/.rodata.cst2
/sys/module/nf_tables/sections/.retpoline_sites
/sys/module/nf_tables/sections/.altinstr_aux
/sys/module/nf_tables/sections/.rodata.str1.8
/sys/module/virtio_gpu/notes/.note.Linux
/sys/module/virtio_gpu/notes/.note.gnu.build-id
/sys/module/virtio_gpu/sections/.note.Linux
/sys/module/virtio_gpu/sections/.static_call_sites
/sys/module/virtio_gpu/sections/.strtab
/sys/module/virtio_gpu/sections/.exit.text
/sys/module/virtio_gpu/sections/.exit.data
/sys/module/virtio_gpu/sections/.bss
/sys/module/virtio_gpu/sections/.static_call.text
/sys/module/virtio_gpu/sections/.return_sites
/sys/module/virtio_gpu/sections/.gnu.linkonce.this_module
/sys/module/virtio_gpu/sections/.symtab
/sys/module/virtio_gpu/sections/.rodata
/sys/module/virtio_gpu/sections/.init.text
/sys/module/virtio_gpu/sections/.note.gnu.build-id
/sys/module/virtio_gpu/sections/.text
/sys/module/virtio_gpu/sections/.init.data
/sys/module/virtio_gpu/sections/.call_sites
/sys/module/virtio_gpu/sections/.data
/sys/module/virtio_gpu/sections/.smp_locks
/sys/module/virtio_gpu/sections/.rodata.str1.1
/sys/module/virtio_gpu/sections/.text.unlikely
/sys/module/virtio_gpu/sections/.retpoline_sites
/sys/module/virtio_gpu/sections/.rodata.str1.8
/sys/module/virtio_gpu/sections/.ref.data
/sys/module/x_tables/notes/.note.Linux
/sys/module/x_tables/notes/.note.gnu.build-id
/sys/module/x_tables/sections/.altinstructions
/sys/module/x_tables/sections/.data..read_mostly
/sys/module/x_tables/sections/.note.Linux
/sys/module/x_tables/sections/.static_call_sites
/sys/module/x_tables/sections/.strtab
/sys/module/x_tables/sections/.exit.text
/sys/module/x_tables/sections/.exit.data
/sys/module/x_tables/sections/.bss
/sys/module/x_tables/sections/.return_sites
/sys/module/x_tables/sections/.gnu.linkonce.this_module
/sys/module/x_tables/sections/.symtab
/sys/module/x_tables/sections/.rodata
/sys/module/x_tables/sections/.init.text
/sys/module/x_tables/sections/.note.gnu.build-id
/sys/module/x_tables/sections/.text
/sys/module/x_tables/sections/.init.data
/sys/module/x_tables/sections/.call_sites
/sys/module/x_tables/sections/.data
/sys/module/x_tables/sections/.altinstr_replacement
/sys/module/x_tables/sections/.rodata.str1.1
/sys/module/x_tables/sections/.retpoline_sites
/sys/module/x_tables/sections/.rodata.str1.8
/sys/module/xhci_pci/notes/.note.Linux
/sys/module/xhci_pci/notes/.note.gnu.build-id
/sys/module/xhci_pci/sections/.data..read_mostly
/sys/module/xhci_pci/sections/.note.Linux
/sys/module/xhci_pci/sections/.static_call_sites
/sys/module/xhci_pci/sections/.strtab
/sys/module/xhci_pci/sections/.exit.text
/sys/module/xhci_pci/sections/.exit.data
/sys/module/xhci_pci/sections/.init.rodata
/sys/module/xhci_pci/sections/.return_sites
/sys/module/xhci_pci/sections/.gnu.linkonce.this_module
/sys/module/xhci_pci/sections/.symtab
/sys/module/xhci_pci/sections/.rodata
/sys/module/xhci_pci/sections/.init.text
/sys/module/xhci_pci/sections/.note.gnu.build-id
/sys/module/xhci_pci/sections/.text
/sys/module/xhci_pci/sections/.init.data
/sys/module/xhci_pci/sections/.call_sites
/sys/module/xhci_pci/sections/.data
/sys/module/xhci_pci/sections/.smp_locks
/sys/module/xhci_pci/sections/.rodata.str1.1
/sys/module/xhci_pci/sections/.rodata.str1.8
/sys/module/binfmt_misc/notes/.note.Linux
/sys/module/binfmt_misc/notes/.note.gnu.build-id
/sys/module/binfmt_misc/sections/.note.Linux
/sys/module/binfmt_misc/sections/.strtab
/sys/module/binfmt_misc/sections/.exit.text
/sys/module/binfmt_misc/sections/.exit.data
/sys/module/binfmt_misc/sections/.return_sites
/sys/module/binfmt_misc/sections/.gnu.linkonce.this_module
/sys/module/binfmt_misc/sections/.symtab
/sys/module/binfmt_misc/sections/.rodata
/sys/module/binfmt_misc/sections/.init.text
/sys/module/binfmt_misc/sections/.note.gnu.build-id
/sys/module/binfmt_misc/sections/.text
/sys/module/binfmt_misc/sections/.init.data
/sys/module/binfmt_misc/sections/.call_sites
/sys/module/binfmt_misc/sections/.data
/sys/module/binfmt_misc/sections/.smp_locks
/sys/module/binfmt_misc/sections/.rodata.str1.1
/sys/module/binfmt_misc/sections/.text.unlikely
/sys/module/binfmt_misc/sections/.rodata.str1.8
/sys/module/i2c_i801/notes/.note.Linux
/sys/module/i2c_i801/notes/.note.gnu.build-id
/sys/module/i2c_i801/sections/.altinstructions
/sys/module/i2c_i801/sections/.note.Linux
/sys/module/i2c_i801/sections/.strtab
/sys/module/i2c_i801/sections/.exit.text
/sys/module/i2c_i801/sections/.exit.data
/sys/module/i2c_i801/sections/.bss
/sys/module/i2c_i801/sections/.return_sites
/sys/module/i2c_i801/sections/.gnu.linkonce.this_module
/sys/module/i2c_i801/sections/.symtab
/sys/module/i2c_i801/sections/.rodata
/sys/module/i2c_i801/sections/.init.text
/sys/module/i2c_i801/sections/.note.gnu.build-id
/sys/module/i2c_i801/sections/.text
/sys/module/i2c_i801/sections/.init.data
/sys/module/i2c_i801/sections/.call_sites
/sys/module/i2c_i801/sections/.data
/sys/module/i2c_i801/sections/.altinstr_replacement
/sys/module/i2c_i801/sections/.smp_locks
/sys/module/i2c_i801/sections/.rodata.str1.1
/sys/module/i2c_i801/sections/.data..ro_after_init
/sys/module/i2c_i801/sections/.text.unlikely
/sys/module/i2c_i801/sections/.retpoline_sites
/sys/module/i2c_i801/sections/.rodata.str1.8
/sys/module/kvm/notes/.note.Linux
/sys/module/kvm/notes/.note.gnu.build-id
/sys/module/kvm/sections/.altinstructions
/sys/module/kvm/sections/.data.once
/sys/module/kvm/sections/.data..read_mostly
/sys/module/kvm/sections/.note.Linux
/sys/module/kvm/sections/.static_call_sites
/sys/module/kvm/sections/.strtab
/sys/module/kvm/sections/.exit.text
/sys/module/kvm/sections/.exit.data
/sys/module/kvm/sections/.bss
/sys/module/kvm/sections/.static_call.text
/sys/module/kvm/sections/.return_sites
/sys/module/kvm/sections/.gnu.linkonce.this_module
/sys/module/kvm/sections/.symtab
/sys/module/kvm/sections/.rodata
/sys/module/kvm/sections/.init.text
/sys/module/kvm/sections/.note.gnu.build-id
/sys/module/kvm/sections/.text
/sys/module/kvm/sections/.init.data
/sys/module/kvm/sections/.call_sites
/sys/module/kvm/sections/.data
/sys/module/kvm/sections/.altinstr_replacement
/sys/module/kvm/sections/.smp_locks
/sys/module/kvm/sections/.rodata.str1.1
/sys/module/kvm/sections/.data..ro_after_init
/sys/module/kvm/sections/.text.unlikely
/sys/module/kvm/sections/.rodata.cst2
/sys/module/kvm/sections/.noinstr.text
/sys/module/kvm/sections/.retpoline_sites
/sys/module/kvm/sections/.altinstr_aux
/sys/module/kvm/sections/.rodata.str1.8
/sys/module/kvm/sections/.ref.data
/sys/module/llc/notes/.note.Linux
/sys/module/llc/notes/.note.gnu.build-id
/sys/module/llc/sections/.data..read_mostly
/sys/module/llc/sections/.note.Linux
/sys/module/llc/sections/.strtab
/sys/module/llc/sections/.exit.text
/sys/module/llc/sections/.exit.data
/sys/module/llc/sections/.bss
/sys/module/llc/sections/.return_sites
/sys/module/llc/sections/.gnu.linkonce.this_module
/sys/module/llc/sections/.symtab
/sys/module/llc/sections/.init.text
/sys/module/llc/sections/.note.gnu.build-id
/sys/module/llc/sections/.text
/sys/module/llc/sections/.init.data
/sys/module/llc/sections/.call_sites
/sys/module/llc/sections/.data
/sys/module/llc/sections/.smp_locks
/sys/module/llc/sections/.rodata.str1.1
/sys/module/llc/sections/.rodata.cst2
/sys/module/llc/sections/.retpoline_sites
/sys/module/llc/sections/.rodata.str1.8
/sys/module/aesni_intel/notes/.note.Linux
/sys/module/aesni_intel/notes/.note.gnu.build-id
/sys/module/aesni_intel/sections/.rodata.cst16.SHUF_MASK
/sys/module/aesni_intel/sections/.rodata.cst16.TWOONE
/sys/module/aesni_intel/sections/.rodata.cst16.ONE
/sys/module/aesni_intel/sections/.rodata.cst16.MASK2
/sys/module/aesni_intel/sections/.rodata.cst16.F_MIN_MASK
/sys/module/aesni_intel/sections/.note.Linux
/sys/module/aesni_intel/sections/.static_call_sites
/sys/module/aesni_intel/sections/.rodata.cst16.enc
/sys/module/aesni_intel/sections/.strtab
/sys/module/aesni_intel/sections/.exit.text
/sys/module/aesni_intel/sections/.exit.data
/sys/module/aesni_intel/sections/.bss
/sys/module/aesni_intel/sections/.rodata.cst16.POLY
/sys/module/aesni_intel/sections/.rodata.cst16.POLY2
/sys/module/aesni_intel/sections/.static_call.text
/sys/module/aesni_intel/sections/.return_sites
/sys/module/aesni_intel/sections/.gnu.linkonce.this_module
/sys/module/aesni_intel/sections/.symtab
/sys/module/aesni_intel/sections/.rodata
/sys/module/aesni_intel/sections/.init.text
/sys/module/aesni_intel/sections/.note.gnu.build-id
/sys/module/aesni_intel/sections/.text
/sys/module/aesni_intel/sections/.rodata.cst16.MASK1
/sys/module/aesni_intel/sections/.init.data
/sys/module/aesni_intel/sections/.call_sites
/sys/module/aesni_intel/sections/.data
/sys/module/aesni_intel/sections/.rodata.cst16.gf128mul_x_ble_mask
/sys/module/aesni_intel/sections/.data..ro_after_init
/sys/module/aesni_intel/sections/.rodata.cst16.dec
/sys/module/aesni_intel/sections/.rodata.cst16.ONEf
/sys/module/aesni_intel/sections/.rodata.str1.8
/sys/module/crct10dif_pclmul/notes/.note.Linux
/sys/module/crct10dif_pclmul/notes/.note.gnu.build-id
/sys/module/crct10dif_pclmul/sections/.note.Linux
/sys/module/crct10dif_pclmul/sections/.strtab
/sys/module/crct10dif_pclmul/sections/.exit.text
/sys/module/crct10dif_pclmul/sections/.rodata.cst16.mask1
/sys/module/crct10dif_pclmul/sections/.exit.data
/sys/module/crct10dif_pclmul/sections/.return_sites
/sys/module/crct10dif_pclmul/sections/.gnu.linkonce.this_module
/sys/module/crct10dif_pclmul/sections/.symtab
/sys/module/crct10dif_pclmul/sections/.rodata
/sys/module/crct10dif_pclmul/sections/.init.text
/sys/module/crct10dif_pclmul/sections/.note.gnu.build-id
/sys/module/crct10dif_pclmul/sections/.text
/sys/module/crct10dif_pclmul/sections/.rodata.cst16.bswap_mask
/sys/module/crct10dif_pclmul/sections/.rodata.cst32.byteshift_table
/sys/module/crct10dif_pclmul/sections/.init.data
/sys/module/crct10dif_pclmul/sections/.call_sites
/sys/module/crct10dif_pclmul/sections/.data
/sys/module/crct10dif_pclmul/sections/.rodata.cst16.mask2
/sys/module/nft_chain_nat/notes/.note.Linux
/sys/module/nft_chain_nat/notes/.note.gnu.build-id
/sys/module/nft_chain_nat/sections/.note.Linux
/sys/module/nft_chain_nat/sections/.strtab
/sys/module/nft_chain_nat/sections/.exit.text
/sys/module/nft_chain_nat/sections/.exit.data
/sys/module/nft_chain_nat/sections/.return_sites
/sys/module/nft_chain_nat/sections/.gnu.linkonce.this_module
/sys/module/nft_chain_nat/sections/.symtab
/sys/module/nft_chain_nat/sections/.rodata
/sys/module/nft_chain_nat/sections/.init.text
/sys/module/nft_chain_nat/sections/.note.gnu.build-id
/sys/module/nft_chain_nat/sections/.text
/sys/module/nft_chain_nat/sections/.init.data
/sys/module/nft_chain_nat/sections/.call_sites
/sys/module/nft_chain_nat/sections/.rodata.str1.1
/sys/module/rapl/notes/.note.Linux
/sys/module/rapl/notes/.note.gnu.build-id
/sys/module/rapl/sections/.altinstructions
/sys/module/rapl/sections/.data..read_mostly
/sys/module/rapl/sections/.note.Linux
/sys/module/rapl/sections/.strtab
/sys/module/rapl/sections/.exit.text
/sys/module/rapl/sections/.exit.data
/sys/module/rapl/sections/.bss
/sys/module/rapl/sections/.init.rodata
/sys/module/rapl/sections/.return_sites
/sys/module/rapl/sections/.gnu.linkonce.this_module
/sys/module/rapl/sections/.symtab
/sys/module/rapl/sections/.init.text
/sys/module/rapl/sections/.note.gnu.build-id
/sys/module/rapl/sections/.text
/sys/module/rapl/sections/.init.data
/sys/module/rapl/sections/.call_sites
/sys/module/rapl/sections/.data
/sys/module/rapl/sections/.altinstr_replacement
/sys/module/rapl/sections/.smp_locks
/sys/module/rapl/sections/.rodata.str1.1
/sys/module/rapl/sections/.text.unlikely
/sys/module/rapl/sections/.retpoline_sites
/sys/module/rapl/sections/.rodata.str1.8
/sys/module/raid456/notes/.note.Linux
/sys/module/raid456/notes/.note.gnu.build-id
/sys/module/raid456/sections/.altinstructions
/sys/module/raid456/sections/.data.once
/sys/module/raid456/sections/.note.Linux
/sys/module/raid456/sections/.static_call_sites
/sys/module/raid456/sections/.strtab
/sys/module/raid456/sections/.exit.data
/sys/module/raid456/sections/.bss
/sys/module/raid456/sections/.return_sites
/sys/module/raid456/sections/.gnu.linkonce.this_module
/sys/module/raid456/sections/.symtab
/sys/module/raid456/sections/.rodata
/sys/module/raid456/sections/.init.text
/sys/module/raid456/sections/.note.gnu.build-id
/sys/module/raid456/sections/.text
/sys/module/raid456/sections/.init.data
/sys/module/raid456/sections/.call_sites
/sys/module/raid456/sections/.data
/sys/module/raid456/sections/.altinstr_replacement
/sys/module/raid456/sections/.smp_locks
/sys/module/raid456/sections/.rodata.str1.1
/sys/module/raid456/sections/.text.unlikely
/sys/module/raid456/sections/.rodata.str1.8
/sys/module/inet_diag/notes/.note.Linux
/sys/module/inet_diag/notes/.note.gnu.build-id
/sys/module/inet_diag/sections/.note.Linux
/sys/module/inet_diag/sections/.static_call_sites
/sys/module/inet_diag/sections/.strtab
/sys/module/inet_diag/sections/.exit.text
/sys/module/inet_diag/sections/.exit.data
/sys/module/inet_diag/sections/.bss
/sys/module/inet_diag/sections/.return_sites
/sys/module/inet_diag/sections/.gnu.linkonce.this_module
/sys/module/inet_diag/sections/.symtab
/sys/module/inet_diag/sections/.rodata
/sys/module/inet_diag/sections/.init.text
/sys/module/inet_diag/sections/.note.gnu.build-id
/sys/module/inet_diag/sections/.text
/sys/module/inet_diag/sections/.init.data
/sys/module/inet_diag/sections/.call_sites
/sys/module/inet_diag/sections/.data
/sys/module/inet_diag/sections/.smp_locks
/sys/module/inet_diag/sections/.rodata.str1.1
/sys/module/inet_diag/sections/.text.unlikely
/sys/module/inet_diag/sections/.rodata.cst2
/sys/module/inet_diag/sections/.retpoline_sites
/sys/module/inet_diag/sections/.rodata.str1.8
/sys/module/kvm_intel/notes/.note.Linux
/sys/module/kvm_intel/notes/.note.gnu.build-id
/sys/module/kvm_intel/sections/.altinstructions
/sys/module/kvm_intel/sections/.data.once
/sys/module/kvm_intel/sections/.data..read_mostly
/sys/module/kvm_intel/sections/.note.Linux
/sys/module/kvm_intel/sections/.static_call_sites
/sys/module/kvm_intel/sections/.strtab
/sys/module/kvm_intel/sections/.exit.data
/sys/module/kvm_intel/sections/.bss
/sys/module/kvm_intel/sections/.return_sites
/sys/module/kvm_intel/sections/.gnu.linkonce.this_module
/sys/module/kvm_intel/sections/.symtab
/sys/module/kvm_intel/sections/.rodata
/sys/module/kvm_intel/sections/.init.text
/sys/module/kvm_intel/sections/.note.gnu.build-id
/sys/module/kvm_intel/sections/.text
/sys/module/kvm_intel/sections/.init.data
/sys/module/kvm_intel/sections/.call_sites
/sys/module/kvm_intel/sections/.data
/sys/module/kvm_intel/sections/.altinstr_replacement
/sys/module/kvm_intel/sections/.smp_locks
/sys/module/kvm_intel/sections/.rodata.str1.1
/sys/module/kvm_intel/sections/.data..ro_after_init
/sys/module/kvm_intel/sections/.text.unlikely
/sys/module/kvm_intel/sections/.rodata.cst2
/sys/module/kvm_intel/sections/.noinstr.text
/sys/module/kvm_intel/sections/.retpoline_sites
/sys/module/kvm_intel/sections/.altinstr_aux
/sys/module/kvm_intel/sections/.rodata.str1.8
/sys/module/psmouse/notes/.note.Linux
/sys/module/psmouse/notes/.note.gnu.build-id
/sys/module/psmouse/sections/.altinstructions
/sys/module/psmouse/sections/.note.Linux
/sys/module/psmouse/sections/.static_call_sites
/sys/module/psmouse/sections/.strtab
/sys/module/psmouse/sections/.exit.text
/sys/module/psmouse/sections/.exit.data
/sys/module/psmouse/sections/.bss
/sys/module/psmouse/sections/.init.rodata
/sys/module/psmouse/sections/.return_sites
/sys/module/psmouse/sections/.gnu.linkonce.this_module
/sys/module/psmouse/sections/.symtab
/sys/module/psmouse/sections/.rodata
/sys/module/psmouse/sections/.init.text
/sys/module/psmouse/sections/.note.gnu.build-id
/sys/module/psmouse/sections/.text
/sys/module/psmouse/sections/.init.data
/sys/module/psmouse/sections/.call_sites
/sys/module/psmouse/sections/.data
/sys/module/psmouse/sections/.altinstr_replacement
/sys/module/psmouse/sections/.smp_locks
/sys/module/psmouse/sections/.rodata.str1.1
/sys/module/psmouse/sections/.text.unlikely
/sys/module/psmouse/sections/.retpoline_sites
/sys/module/psmouse/sections/.altinstr_aux
/sys/module/psmouse/sections/.rodata.str1.8
/sys/module/ip_tables/notes/.note.Linux
/sys/module/ip_tables/notes/.note.gnu.build-id
/sys/module/ip_tables/sections/.altinstructions
/sys/module/ip_tables/sections/.data..read_mostly
/sys/module/ip_tables/sections/.note.Linux
/sys/module/ip_tables/sections/.static_call_sites
/sys/module/ip_tables/sections/.strtab
/sys/module/ip_tables/sections/.exit.text
/sys/module/ip_tables/sections/.exit.data
/sys/module/ip_tables/sections/.return_sites
/sys/module/ip_tables/sections/.gnu.linkonce.this_module
/sys/module/ip_tables/sections/.symtab
/sys/module/ip_tables/sections/.rodata
/sys/module/ip_tables/sections/.init.text
/sys/module/ip_tables/sections/.note.gnu.build-id
/sys/module/ip_tables/sections/.text
/sys/module/ip_tables/sections/.init.data
/sys/module/ip_tables/sections/.call_sites
/sys/module/ip_tables/sections/.data
/sys/module/ip_tables/sections/.altinstr_replacement
/sys/module/ip_tables/sections/.rodata.str1.1
/sys/module/ip_tables/sections/.text.unlikely
/sys/module/ip_tables/sections/.retpoline_sites
/sys/module/ip_tables/sections/.rodata.str1.8
/sys/module/sha256_ssse3/notes/.note.Linux
/sys/module/sha256_ssse3/notes/.note.gnu.build-id
/sys/module/sha256_ssse3/sections/.rodata.cst16.PSHUFFLE_BYTE_FLIP_MASK
/sys/module/sha256_ssse3/sections/.rodata.cst16._SHUF_DC00
/sys/module/sha256_ssse3/sections/.rodata.cst16._SHUF_00BA
/sys/module/sha256_ssse3/sections/.rodata.cst32.PSHUFFLE_BYTE_FLIP_MASK
/sys/module/sha256_ssse3/sections/.data.once
/sys/module/sha256_ssse3/sections/.note.Linux
/sys/module/sha256_ssse3/sections/.strtab
/sys/module/sha256_ssse3/sections/.rodata.cst32._SHUF_DC00
/sys/module/sha256_ssse3/sections/.exit.text
/sys/module/sha256_ssse3/sections/.exit.data
/sys/module/sha256_ssse3/sections/.rodata.cst32._SHUF_00BA
/sys/module/sha256_ssse3/sections/.rodata.cst512.K256
/sys/module/sha256_ssse3/sections/.return_sites
/sys/module/sha256_ssse3/sections/.gnu.linkonce.this_module
/sys/module/sha256_ssse3/sections/.symtab
/sys/module/sha256_ssse3/sections/.rodata
/sys/module/sha256_ssse3/sections/.init.text
/sys/module/sha256_ssse3/sections/.note.gnu.build-id
/sys/module/sha256_ssse3/sections/.text
/sys/module/sha256_ssse3/sections/.init.data
/sys/module/sha256_ssse3/sections/.call_sites
/sys/module/sha256_ssse3/sections/.data
/sys/module/sha256_ssse3/sections/.rodata.str1.1
/sys/module/sha256_ssse3/sections/.rodata.cst256.K256
/sys/module/sha256_ssse3/sections/.text.unlikely
/sys/module/sha256_ssse3/sections/.retpoline_sites
/sys/module/sha256_ssse3/sections/.rodata.str1.8
/sys/module/intel_rapl_common/notes/.note.Linux
/sys/module/intel_rapl_common/notes/.note.gnu.build-id
/sys/module/intel_rapl_common/sections/.altinstructions
/sys/module/intel_rapl_common/sections/.note.Linux
/sys/module/intel_rapl_common/sections/.strtab
/sys/module/intel_rapl_common/sections/.exit.text
/sys/module/intel_rapl_common/sections/.exit.data
/sys/module/intel_rapl_common/sections/.bss
/sys/module/intel_rapl_common/sections/.init.rodata
/sys/module/intel_rapl_common/sections/.return_sites
/sys/module/intel_rapl_common/sections/.gnu.linkonce.this_module
/sys/module/intel_rapl_common/sections/.symtab
/sys/module/intel_rapl_common/sections/.rodata
/sys/module/intel_rapl_common/sections/.init.text
/sys/module/intel_rapl_common/sections/.note.gnu.build-id
/sys/module/intel_rapl_common/sections/.text
/sys/module/intel_rapl_common/sections/.init.data
/sys/module/intel_rapl_common/sections/.call_sites
/sys/module/intel_rapl_common/sections/.data
/sys/module/intel_rapl_common/sections/.altinstr_replacement
/sys/module/intel_rapl_common/sections/.rodata.str1.1
/sys/module/intel_rapl_common/sections/.text.unlikely
/sys/module/intel_rapl_common/sections/.retpoline_sites
/sys/module/intel_rapl_common/sections/.rodata.str1.8
/sys/module/xfrm_user/notes/.note.Linux
/sys/module/xfrm_user/notes/.note.gnu.build-id
/sys/module/xfrm_user/sections/.note.Linux
/sys/module/xfrm_user/sections/.strtab
/sys/module/xfrm_user/sections/.exit.text
/sys/module/xfrm_user/sections/.exit.data
/sys/module/xfrm_user/sections/.return_sites
/sys/module/xfrm_user/sections/.gnu.linkonce.this_module
/sys/module/xfrm_user/sections/.symtab
/sys/module/xfrm_user/sections/.rodata
/sys/module/xfrm_user/sections/.init.text
/sys/module/xfrm_user/sections/.note.gnu.build-id
/sys/module/xfrm_user/sections/.text
/sys/module/xfrm_user/sections/.init.data
/sys/module/xfrm_user/sections/.call_sites
/sys/module/xfrm_user/sections/.data
/sys/module/xfrm_user/sections/.smp_locks
/sys/module/xfrm_user/sections/.rodata.str1.1
/sys/module/xfrm_user/sections/.retpoline_sites
/sys/module/xfrm_user/sections/.rodata.str1.8
/sys/module/xt_MASQUERADE/notes/.note.Linux
/sys/module/xt_MASQUERADE/notes/.note.gnu.build-id
/sys/module/xt_MASQUERADE/sections/.data..read_mostly
/sys/module/xt_MASQUERADE/sections/.note.Linux
/sys/module/xt_MASQUERADE/sections/.strtab
/sys/module/xt_MASQUERADE/sections/.exit.text
/sys/module/xt_MASQUERADE/sections/.exit.data
/sys/module/xt_MASQUERADE/sections/.return_sites
/sys/module/xt_MASQUERADE/sections/.gnu.linkonce.this_module
/sys/module/xt_MASQUERADE/sections/.symtab
/sys/module/xt_MASQUERADE/sections/.rodata
/sys/module/xt_MASQUERADE/sections/.init.text
/sys/module/xt_MASQUERADE/sections/.note.gnu.build-id
/sys/module/xt_MASQUERADE/sections/.text
/sys/module/xt_MASQUERADE/sections/.init.data
/sys/module/xt_MASQUERADE/sections/.call_sites
/sys/module/xt_MASQUERADE/sections/.rodata.str1.1
/sys/module/xt_MASQUERADE/sections/.rodata.str1.8
/sys/module/async_raid6_recov/notes/.note.Linux
/sys/module/async_raid6_recov/notes/.note.gnu.build-id
/sys/module/async_raid6_recov/sections/.note.Linux
/sys/module/async_raid6_recov/sections/.strtab
/sys/module/async_raid6_recov/sections/.return_sites
/sys/module/async_raid6_recov/sections/.gnu.linkonce.this_module
/sys/module/async_raid6_recov/sections/.symtab
/sys/module/async_raid6_recov/sections/.rodata
/sys/module/async_raid6_recov/sections/.note.gnu.build-id
/sys/module/async_raid6_recov/sections/.text
/sys/module/async_raid6_recov/sections/.call_sites
/sys/module/async_raid6_recov/sections/.data
/sys/module/async_raid6_recov/sections/.smp_locks
/sys/module/async_raid6_recov/sections/.rodata.str1.1
/sys/module/async_raid6_recov/sections/.retpoline_sites
/sys/module/async_raid6_recov/sections/.rodata.str1.8
/sys/module/stp/notes/.note.Linux
/sys/module/stp/notes/.note.gnu.build-id
/sys/module/stp/sections/.data..read_mostly
/sys/module/stp/sections/.note.Linux
/sys/module/stp/sections/.strtab
/sys/module/stp/sections/.bss
/sys/module/stp/sections/.return_sites
/sys/module/stp/sections/.gnu.linkonce.this_module
/sys/module/stp/sections/.symtab
/sys/module/stp/sections/.note.gnu.build-id
/sys/module/stp/sections/.text
/sys/module/stp/sections/.call_sites
/sys/module/stp/sections/.data
/sys/module/stp/sections/.smp_locks
/sys/module/stp/sections/.retpoline_sites
/sys/module/stp/sections/.rodata.str1.8
/sys/module/crc32_pclmul/notes/.note.Linux
/sys/module/crc32_pclmul/notes/.note.gnu.build-id
/sys/module/crc32_pclmul/sections/.note.Linux
/sys/module/crc32_pclmul/sections/.strtab
/sys/module/crc32_pclmul/sections/.exit.text
/sys/module/crc32_pclmul/sections/.exit.data
/sys/module/crc32_pclmul/sections/.return_sites
/sys/module/crc32_pclmul/sections/.gnu.linkonce.this_module
/sys/module/crc32_pclmul/sections/.symtab
/sys/module/crc32_pclmul/sections/.rodata
/sys/module/crc32_pclmul/sections/.init.text
/sys/module/crc32_pclmul/sections/.note.gnu.build-id
/sys/module/crc32_pclmul/sections/.text
/sys/module/crc32_pclmul/sections/.init.data
/sys/module/crc32_pclmul/sections/.call_sites
/sys/module/crc32_pclmul/sections/.data
/sys/module/crc32_pclmul/sections/.rodata.str1.8
/sys/module/ib_core/notes/.note.Linux
/sys/module/ib_core/notes/.note.gnu.build-id
/sys/module/ib_core/sections/.altinstructions
/sys/module/ib_core/sections/.data.once
/sys/module/ib_core/sections/.note.Linux
/sys/module/ib_core/sections/.static_call_sites
/sys/module/ib_core/sections/.strtab
/sys/module/ib_core/sections/.exit.text
/sys/module/ib_core/sections/.exit.data
/sys/module/ib_core/sections/.bss
/sys/module/ib_core/sections/.static_call.text
/sys/module/ib_core/sections/.return_sites
/sys/module/ib_core/sections/.gnu.linkonce.this_module
/sys/module/ib_core/sections/.symtab
/sys/module/ib_core/sections/.rodata
/sys/module/ib_core/sections/.init.text
/sys/module/ib_core/sections/.note.gnu.build-id
/sys/module/ib_core/sections/.text
/sys/module/ib_core/sections/.init.data
/sys/module/ib_core/sections/.call_sites
/sys/module/ib_core/sections/.data
/sys/module/ib_core/sections/.altinstr_replacement
/sys/module/ib_core/sections/.smp_locks
/sys/module/ib_core/sections/.rodata.str1.1
/sys/module/ib_core/sections/.text.unlikely
/sys/module/ib_core/sections/.retpoline_sites
/sys/module/ib_core/sections/.rodata.str1.8
/sys/module/ib_core/sections/.ref.data
/sys/module/cfg80211/notes/.note.Linux
/sys/module/cfg80211/notes/.note.gnu.build-id
/sys/module/cfg80211/sections/.altinstructions
/sys/module/cfg80211/sections/.data.once
/sys/module/cfg80211/sections/.note.Linux
/sys/module/cfg80211/sections/.static_call_sites
/sys/module/cfg80211/sections/.strtab
/sys/module/cfg80211/sections/.exit.text
/sys/module/cfg80211/sections/.exit.data
/sys/module/cfg80211/sections/.bss
/sys/module/cfg80211/sections/.static_call.text
/sys/module/cfg80211/sections/.return_sites
/sys/module/cfg80211/sections/.gnu.linkonce.this_module
/sys/module/cfg80211/sections/.symtab
/sys/module/cfg80211/sections/.rodata
/sys/module/cfg80211/sections/.init.text
/sys/module/cfg80211/sections/.note.gnu.build-id
/sys/module/cfg80211/sections/.text
/sys/module/cfg80211/sections/.init.data
/sys/module/cfg80211/sections/.call_sites
/sys/module/cfg80211/sections/.data
/sys/module/cfg80211/sections/.altinstr_replacement
/sys/module/cfg80211/sections/.smp_locks
/sys/module/cfg80211/sections/.rodata.str1.1
/sys/module/cfg80211/sections/.data..ro_after_init
/sys/module/cfg80211/sections/.text.unlikely
/sys/module/cfg80211/sections/.rodata.cst2
/sys/module/cfg80211/sections/.retpoline_sites
/sys/module/cfg80211/sections/.rodata.str1.8
/sys/module/cfg80211/sections/.ref.data
/sys/module/polyval_clmulni/notes/.note.Linux
/sys/module/polyval_clmulni/notes/.note.gnu.build-id
/sys/module/polyval_clmulni/sections/.note.Linux
/sys/module/polyval_clmulni/sections/.strtab
/sys/module/polyval_clmulni/sections/.exit.text
/sys/module/polyval_clmulni/sections/.rodata.cst16.gstar
/sys/module/polyval_clmulni/sections/.exit.data
/sys/module/polyval_clmulni/sections/.return_sites
/sys/module/polyval_clmulni/sections/.gnu.linkonce.this_module
/sys/module/polyval_clmulni/sections/.symtab
/sys/module/polyval_clmulni/sections/.rodata
/sys/module/polyval_clmulni/sections/.init.text
/sys/module/polyval_clmulni/sections/.note.gnu.build-id
/sys/module/polyval_clmulni/sections/.text
/sys/module/polyval_clmulni/sections/.init.data
/sys/module/polyval_clmulni/sections/.call_sites
/sys/module/polyval_clmulni/sections/.data
/sys/module/polyval_clmulni/sections/.rodata.str1.8
/sys/module/mic_drop/notes/.note.Linux
/sys/module/mic_drop/notes/.note.gnu.build-id
/sys/module/mic_drop/sections/.note.Linux
/sys/module/mic_drop/sections/.strtab
/sys/module/mic_drop/sections/.exit.data
/sys/module/mic_drop/sections/.bss
/sys/module/mic_drop/sections/.return_sites
/sys/module/mic_drop/sections/.gnu.linkonce.this_module
/sys/module/mic_drop/sections/.symtab
/sys/module/mic_drop/sections/.rodata
/sys/module/mic_drop/sections/.note.gnu.build-id
/sys/module/mic_drop/sections/.text
/sys/module/mic_drop/sections/.init.data
/sys/module/mic_drop/sections/.call_sites
/sys/module/mic_drop/sections/.data
/sys/module/mic_drop/sections/.rodata.str1.1
/sys/module/mic_drop/sections/.retpoline_sites
/sys/module/mic_drop/sections/.rodata.str1.8
/.dockerenv
root@capytol:~# alias
root@capytol:~# env
HOSTNAME=capytol
PWD=/home/mayor
HOME=/home/mayor
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
root@capytol:~# cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf
